### ISSUE TITLE
System response to clearing memory cache

### ISSUE THREAD

**Issue by yluvs** [liaralabs/swizzin#104]
Hello,
I was wondering if there is any way to clear the system response message after clearing RAM cache in the control panel.
I use the "clear memory cache" tool about twice or thrice a week. After a while, the system response message becomes so long that I find it very difficult to close the message window.
![capture](https://user-images.githubusercontent.com/29858008/39945006-6475d30e-559b-11e8-8a93-026841f469c5.PNG)
Any help would be greatly appreciated. 
Thank you.

**Comment by williamstorm1** [comment]
i also have the same issue :(
aswell as many others.

**Comment by liaralabs** [comment]
Fixed on the panel side. "Close & Refresh" button should now clear the dialog box after each press.

ca823cf55454541d1b31b10e0ad32d8418bb1ab0
