### ISSUE TITLE
CFW install breaks server

### ISSUE THREAD

**Issue by The-OMG** [liaralabs/swizzin#106]
OS: Ubuntu Server 18.04

I am installing everything on a fresh install. Everything seems to be fine until I install CFW. Once CFW installs, I can longer reach my server in any way. Looking at lsof, ufw and iptables shows that the ssh server is listening on port 22 but connection times out.

**Comment by liaralabs** [comment]
CSF has been removed entirely, thus this issue is no longer relevant
