### ISSUE TITLE
stuck at "Updating system and grabbing core dependencies"

### ISSUE THREAD

**Issue by ammar0466** [liaralabs/swizzin#107]
im using ubuntu 16.04
install as root

**Comment by acoolmanfromnowhere** [comment]
Try doing a   "sudo apt-get update && sudo apt-get upgrade" before running the script. Could be the grub upgrade screen that's blocking it.

**Comment by liaralabs** [comment]
This is the correct solution -- sometimes there are upgrades that require user intervention. You can either press enter when it's stuck and it will kick apt along or you can run apt update and upgrade manually before install to allow yourself an interactive upgrade.
