### ISSUE TITLE
PHP Errors

### ISSUE THREAD

**Issue by copcopcopcop** [liaralabs/swizzin#108]
My NGINX error logs are getting flooded with PHP errors after running the script on fresh installs of Debian 8+ 9 and Ubuntu 16.04.

I think the error might be related to PHP v7.0 - would you suggest upgrading/downgrading to 7.2 or 5.6? Looks like 5.6 is available for newer distros via Sury's repo.

`PHP Warning:  Declaration of rxmlrpcfix::run() should be compatible with rXMLRPCRequest::run($trusted = true) in /srv/rutorrent/plugins/filemanager/xmlfix.php on line 0" while reading response header from upstream, client: 10.0.200.2, server: _, request: "POST /rutorrent/plugins/filemanager/flm.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:",`

**Comment by liaralabs** [comment]
I can't say I recommend downgrading to 5.6 at this point.

These are warnings, not errors and this is related to the filemanager plugin which I do not write or control. If they bother you, I suggest contacting the dev of filemanager or disabling error reporting in your php.ini
