### ISSUE TITLE
Ombi not working

### ISSUE THREAD

**Issue by acoolmanfromnowhere** [liaralabs/swizzin#109]
I'm on Ubuntu Ubuntu-1604-xenial-64-nextcloud and I did a fresh install of Swizzin. On installation I get the following error:
Installing ombi
OKdating dependencies ...
grep: /etc/nginx/apps/ombi.conf: No such file or directory
Ombi Installation Complete!

Trying to access Ombi gives me this error:
502 Bad Gateway
nginx

**Comment by liaralabs** [comment]
A restart of the ombi service should fix this. I had been using `systemctl start ombi` but ombi is already running due to the apt install -- I am changing this to restart, which will fix this for future installs.

**Comment by darkneo29** [comment]
Same issue.  Ombi is red in panel and i get the 502 bad gateway error.  Fresh install

**Comment by darkneo29** [comment]
did a apt remove and reinstalled and its working
