### ISSUE TITLE
Seeking feedback regarding the future of the QB Panel

### ISSUE THREAD

**Issue by liaralabs** [liaralabs/swizzin#11]
swizzin is not QuickBox. I have had a lot of feedback regarding things that are "wrong" with the panel lately. I would just like to make it abundantly clear that:

1. I am not a web developer.
2. The QuickBox panel is seen as an addon to swizzin and is not intended to be a core feature like it was in QuickBox.
3. I prefer CLI for pretty much *everything*

At the current moment, fixing issues with the dashboard (like adding packages I have written to the panel, or removing reference to packages that are not available) are **extremely** low priority. It should be known that I am currently toying with the idea of removing the ability to maintain packages from the web browser entirely. Box is an incredible solution and is very easy to use.

I would far rather push this as the package management solution rather than spending my time providing an easy to use graphical interface.

Having to keep the panel up to date with each and every new package will significantly slow the process of adding new applications to the panel as well, because even just a single package requires a significant addition of code to the panel. However, since I don't personally use the panel, I would like to open this discussion up to those that *do* use the panel.

That said, please provide your thoughts and opinions surrounding this topic. Speak now or forever hold your peace!

**Comment by demonotaku** [comment]
I think there should be some type of Panel tying in a solution, however, I do feel things could be done slightly better in regards to items. However, from what I can tell if we could admit a solution like ZNC did with the ZNC.txt file it may quicken the time to deploy software in terms of creating everything.

**Comment by d2dyno** [comment]
I think the web panel package manager lacks too many features and requires an overhaul. So I vote we remove it, and perhaps just list some commands somewhere on the panel, to tell the user how they can install a package.

**Comment by smoresmores** [comment]
I don't really need the Panel, CLI is great and that's how it suppose to be imo. Panel is just a source for problems. As @d2dyno maybe only a web page with a list of commands, and needed links for example, something that is just informative.

**Comment by kanenses** [comment]
I not agree, i think a panel as necessary, quick direct links, root site protectora, maybe a simple panel something as htpc panel... 

:-)

**Comment by olafurnsig** [comment]
Hi,

I'm not currently using Quickbox nor Swizzin, i'm running openflixr which I loved at start but has been becoming a bit of a pain in the ass lately.

But parts of what I like about openflixr are things like that you don't have ( or so I think) :

HTPC manager: http://htpc.io/
Webmin: http://www.webmin.com/
Nzbget
Custom splash page 
Netdata

I am a web developer, I might be able to pitch in with stuff, if you point me to what you need assistance with.

**Comment by d2dyno** [comment]
@olafurnsig I think you may be confused as to what Swizzin is designed for. It's designed for seedboxes, not home theater use. While they may share some features, they certainly aren't aimed at the same hardware/setup. Thus the htpc manager isn't applicable. Why would we need a splash page, I'm not sure. Maybe you can help design a landing/login page for the panel though? Netdata is a planned feature.

This project just started, but is already doing well. I don't think Liara has the kind of time to merge with another developer, plus my earlier comments makes me believe the two are incompatible.

**Comment by olafurnsig** [comment]
If it's just a seedbox why is there a Plex and PlexPy installer script?

HTPC manager is just a panel that connects with various programs that are running, SAB/Nzbget/Plex/ruTorrent/qBittorrent etc and combines them in one UI

**Comment by lizaSB** [comment]
@olafurnsig I appreciate the feedback, but this is not intended to be a call for feature requests. This is solely about what to do with the quickbox panel. I'm not really looking to switch solutions at this time, rather garner feedback regarding current features I am considering removing (like the Web UI for package management)

Netdata is already going to be included (see readme) as an alternative to the panel for those who just want some stats about their box. nzbget may be included at a future date. Webmin is an outright veto.

I'm also somewhat against a splash page too, given that without the panel, a 403 forbidden message is received without logging in. I'm not interested in advertising to bots and crawlers the software that is currently in use on a server for the same reason I disable nginx server tokens.

**Comment by liaralabs** [comment]
@olafurnsig I appreciate the feedback, but this is not intended to be a call for feature requests. This is solely about what to do with the quickbox panel. I'm not really looking to switch solutions at this time, rather garner feedback regarding current features I am considering removing (like the Web UI for package management)

Netdata is already going to be included (see readme) as an alternative to the panel for those who just want some stats about their box. nzbget may be included at a future date. Webmin is an outright veto.

I'm also somewhat against a splash page too, given that without the panel, a 403 forbidden message is received without logging in. I'm not interested in advertising to bots and crawlers the software that is currently in use on a server for the same reason I disable nginx server tokens.

**Comment by liaralabs** [comment]
As of today package management has been disabled in the dashboard.

I won't remove the code yet, but if anyone wants to jump in to bring it up to speed, by all means.

**Comment by maghiridon** [comment]
What I want from the panel is really just the sidebar with a list of links to the various services. I find it incredibly convenient to be able to e.g. go to the Deluge WebUI on a mobile device. The system stats are useful, but as you said, that's also provided by netdata.
