### ISSUE TITLE
Cant access plex and btsync from domain, accessing through IP works fine

### ISSUE THREAD

**Issue by elbasan** [liaralabs/swizzin#111]
As the title says, Opening the dashboard from my domain works fine, but plex and btsync just refuse to connect, accesing from the IP Works fine

**Comment by liaralabs** [comment]
Are you using CloudFlare on your domain?

**Comment by elbasan** [comment]
Yes

**Comment by liaralabs** [comment]
https://support.cloudflare.com/hc/en-us/articles/200169156-Which-ports-will-Cloudflare-work-with-
