### ISSUE TITLE
Jackett now requires mono 5.8+

### ISSUE THREAD

**Issue by jdcrensh** [liaralabs/swizzin#113]
Current versions of Jackett no longer work with the mono version used by Swizzin.

See: https://github.com/Jackett/Jackett/releases/tag/v0.8.1175

**Comment by RikT** [comment]
I would disable the repo in sources and then you can just do apt install mono-devel and it should update it

**Comment by liaralabs** [comment]
I'll work on getting this updated in the repo soon, but the fix is as follows:

Edit /etc/apt/sources.list.d/mono-xamarin.list

And change 4.8 to 5.8 -- save, exit. `apt update && apt upgrade`
