### ISSUE TITLE
Ombi Troubles

### ISSUE THREAD

**Issue by TheSaxophoneSoloist** [liaralabs/swizzin#115]
I have been having problems with ombi ever since i installed ombi, the service will not restart, and the light in the dashboard stays red. I have tried restarting the service manually, and even tried the solution found in #114 of running the command sudo chown -R ombi: /opt/Ombi and it did not help. 

By the way i am running on Ubuntu 16.04.

I have also tried running ombi manually with  /opt/Ombi/Ombi --baseurl /ombi --host http://127.0.0.1:3000, and this is the output:

> Hello, welcome to Ombi
> Valid options are:
> Ombi 3.0.3421-master
> Copyright (C) 2018 Ombi
> 
>   --host       (Default: http://*:5000) Set to a semicolon-separated (;) list
>                of URL prefixes to which the server should respond. For example,
>                http://localhost:123. Use "*" to indicate that the server should
>                listen for requests on any IP address or hostname using the
>                specified port and protocol (for example, http://*:5000). The
>                protocol (http:// or https://) must be included with each URL.
>                Supported formats vary between servers.
> 
>   --storage    Storage path, where we save the logs and database
> 
>   --baseurl    The base URL for reverse proxy scenarios
> 
>   --help       Display this help screen.
> 
>   --version    Display version information.
> 
> 
> 
> We are running on
> /root
> 
> Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is '/root/appsettings.json'.
>    at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
>    at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
>    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
>    at Ombi.Startup..ctor(IHostingEnvironment env) in C:\projects\requestplex\src\Ombi\Startup.cs:line 52
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
>    at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(IServiceProvider hostingServiceProvider, Type startupType, String environmentName)
>    at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__DisplayClass1_0.<UseStartup>b__1(IServiceProvider sp)
>    at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
>    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
>    at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
>    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
>    at Ombi.Program.Main(String[] args) in C:\projects\requestplex\src\Ombi\Program.cs:line 94

**Comment by liaralabs** [comment]
Duplicate #114

**Comment by TheSaxophoneSoloist** [comment]
not trying to be an ass, but this is a different error than what is happening in #114. should i just add this there? they're both closed, and the solution given in #114 does not help.

**Comment by liaralabs** [comment]
Did you update your install with the changes I pushed upon closing #114? I
pushed a solution, not a work around.

**Comment by liaralabs** [comment]
The error you're getting is misleading:
```
We are running on
/root

Unhandled Exception: System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The physical path is '/root/appsettings.json'.
```
This error won't happen when the systemd service is started not from the command line. This essentially tells me that you just attempted to start the command as root from the /root directory. If you want to run the command you need to use the Ombi directory as your working directory (don't ask me why)

Further, if you truly want to test the command from the command line, you would also need to sudo to the ombi user (as that is who the systemd service runs as)
```
sudo -u ombi bash -c "/opt/Ombi/Ombi --baseurl /ombi --host http://127.0.0.1:3000 --storage /etc/Ombi"
```
The `--storage /etc/Ombi` is the update to the systemd service that should fix issues.
