### ISSUE TITLE
how to remove all traces

### ISSUE THREAD

**Issue by bumjrah** [liaralabs/swizzin#116]
I have already removed swizzin user. Given the running install script gave me a ton of programs to install. How do I go about removing them all, in one go? Ala default state.

**Comment by kennydeckers** [comment]
@bumjrah Aren't you better off doing a clean install of the operating system itself?

**Comment by aluo-x** [comment]
Assuming that the user that swizzin was installed under was different, I was able to run
`sudo deluser --remove-all-files swizzin_accname` (replace swizzin_accname)
and delete every folder/file lists here: [https://swizzin.ltd/guides/troubleshooting](https://swizzin.ltd/guides/troubleshooting)
Had to use pkill/kill if a certain file/folder was locked. 

Rebooting the server and I was able to complete a clean install.
