### ISSUE TITLE
Switch Plex servers

### ISSUE THREAD

**Issue by drjohannspector** [liaralabs/swizzin#117]
I need to restore Plex to the default state. I was signed into another server while claiming a server on Swizzin and need to switch them. Cannot be done on the TV view for Plex so I cannot access the switch server button. Having trouble fully removing plex

**Comment by liaralabs** [comment]
I recommend using a web browser to manage such tasks -- while tunnelled if you can to prevent remote access issues.

For the location of data itself on the server, see here:
https://support.plex.tv/articles/202915258-where-is-the-plex-media-server-data-directory-located/
