### ISSUE TITLE
PHP Warning: destroy uninitiali zed session 

### ISSUE THREAD

**Issue by alkalinelito** [liaralabs/swizzin#120]
Everything works perfect, but I keep getting this error on nginx logs, anyone knows how to fix it?

018/08/07 22:56:57 [error] 13944#13944: *95272 FastCGI sent in stderr: "PHP message: PHP Warning:  session_destroy(): Trying to destroy uninitialized session in /srv/panel/inc/config.php on line 2" while reading response header from upstream, client: 198.41.230.196, server: hostname.com, request: "GET /?act=rt&callback=jQuery21408620988134874924_1533686065251&_=1533686077404 HTTP/1.1",upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "hostname.com", referrer: "https://hostname.com/"

**Comment by liaralabs** [comment]
This is an issue with the QB Panel. It has to do with how it's coded and I'm probably not going to dig in and try to fix this as it has done this for as long as I can remember.

Fixes are either: remove the panel or disable php warning reporting in /etc/php/7.0/fpm/php.ini
