### ISSUE TITLE
Unable to install rtorrent via box

### ISSUE THREAD

**Issue by Qwatuz** [liaralabs/swizzin#125]
Originally I had rtorrent installed during the initial setup, but decided to `box remove rtorrent` as I wanted to downgrade to an earlier version.

I then tried to install it with `box install` - 0.9.6 version and it will hang without completing.

`Installing rTorrent Dependencies ...`

`Building xmlrpc-c from source ...`

`Building libtorrent from source ...`

`Building rtorrent from source ...`

`Making <user> directory structure ...`

`Setting permissions on <user> ...`

I have the latest Swizzin installation, tried rebooting etc.

I would be happy to supply logs but i'm not sure where they are. There are no updated ones in /root/logs.

**Comment by liaralabs** [comment]
What OS are you using?

**Comment by Qwatuz** [comment]
Ubuntu 16.04

**Comment by liaralabs** [comment]
You can re-enable logging to /root/logs/install.log if you `touch /tmp/.install.lock`

If you rerun the script with that file present, the log files will hopefully supply you with some insight as to where the installer froze up.

**Comment by Qwatuz** [comment]
Great, that made a log. I had a look through it but couldn't see what the issue is.

https://pastebin.com/TN5ZVAqh


Possibly the "Nothing to be done for" lines?


```
/bin/sh ../libtool  --tag=CXX   --mode=link g++  -g -O2 -g -DDEBUG -pthread    -I/usr/include    -o rtorrent main.o libsub_root.a ui/libsub_ui.a core/libsub_core.a display/libsub_display.a input/libsub_input.a rpc/libsub_rpc.a utils/libsub_utils.a  -lncurses  -lcurl -ltorrent -L/usr/lib   -lxmlrpc_server -lxmlrpc  -lxmlrpc_xmlparse -lxmlrpc_xmltok -lxmlrpc_util -lpthread 
libtool: link: g++ -g -O2 -g -DDEBUG -pthread -I/usr/include -o rtorrent main.o  libsub_root.a ui/libsub_ui.a core/libsub_core.a display/libsub_display.a input/libsub_input.a rpc/libsub_rpc.a utils/libsub_utils.a -lncurses /usr/lib/x86_64-linux-gnu/libcurl.so /usr/lib/libtorrent.so -L/usr/lib -lxmlrpc_server -lxmlrpc -lxmlrpc_xmlparse -lxmlrpc_xmltok -lxmlrpc_util -lpthread -pthread
make[3]: Leaving directory '/tmp/rtorrent/src'
make[2]: Leaving directory '/tmp/rtorrent/src'
Making all in test
make[2]: Entering directory '/tmp/rtorrent/test'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/tmp/rtorrent/test'
make[2]: Entering directory '/tmp/rtorrent'
make[2]: Leaving directory '/tmp/rtorrent'
make[1]: Leaving directory '/tmp/rtorrent'
Making install in doc
make[1]: Entering directory '/tmp/rtorrent/doc'
make[2]: Entering directory '/tmp/rtorrent/doc'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/tmp/rtorrent/doc'
make[1]: Leaving directory '/tmp/rtorrent/doc'
Making install in src
make[1]: Entering directory '/tmp/rtorrent/src'
Making install in core
make[2]: Entering directory '/tmp/rtorrent/src/core'
make[3]: Entering directory '/tmp/rtorrent/src/core'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/tmp/rtorrent/src/core'
make[2]: Leaving directory '/tmp/rtorrent/src/core'
Making install in display
make[2]: Entering directory '/tmp/rtorrent/src/display'
make[3]: Entering directory '/tmp/rtorrent/src/display'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/tmp/rtorrent/src/display'
make[2]: Leaving directory '/tmp/rtorrent/src/display'
Making install in input
make[2]: Entering directory '/tmp/rtorrent/src/input'
make[3]: Entering directory '/tmp/rtorrent/src/input'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/tmp/rtorrent/src/input'
make[2]: Leaving directory '/tmp/rtorrent/src/input'
Making install in rpc
make[2]: Entering directory '/tmp/rtorrent/src/rpc'
make[3]: Entering directory '/tmp/rtorrent/src/rpc'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/tmp/rtorrent/src/rpc'
make[2]: Leaving directory '/tmp/rtorrent/src/rpc'
Making install in ui
make[2]: Entering directory '/tmp/rtorrent/src/ui'
make[3]: Entering directory '/tmp/rtorrent/src/ui'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/tmp/rtorrent/src/ui'
make[2]: Leaving directory '/tmp/rtorrent/src/ui'
Making install in utils
make[2]: Entering directory '/tmp/rtorrent/src/utils'
make[3]: Entering directory '/tmp/rtorrent/src/utils'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/tmp/rtorrent/src/utils'
make[2]: Leaving directory '/tmp/rtorrent/src/utils'
make[2]: Entering directory '/tmp/rtorrent/src'
make[3]: Entering directory '/tmp/rtorrent/src'
 /bin/mkdir -p '/usr/bin'
  /bin/sh ../libtool   --mode=install /usr/bin/install -c rtorrent '/usr/bin'
libtool: install: /usr/bin/install -c rtorrent /usr/bin/rtorrent
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/tmp/rtorrent/src'
make[2]: Leaving directory '/tmp/rtorrent/src'
make[1]: Leaving directory '/tmp/rtorrent/src'
Making install in test
make[1]: Entering directory '/tmp/rtorrent/test'
make[2]: Entering directory '/tmp/rtorrent/test'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/tmp/rtorrent/test'
make[1]: Leaving directory '/tmp/rtorrent/test'
make[1]: Entering directory '/tmp/rtorrent'
make[2]: Entering directory '/tmp/rtorrent'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/tmp/rtorrent'
make[1]: Leaving directory '/tmp/rtorrent'
```

**Comment by Qwatuz** [comment]
@liaralabs were you able to have a quick look at the log? I understand you're quite busy!

**Comment by liaralabs** [comment]
Have you tried hitting enter when the installer freezes? The package itself hasn't been tested for remove/reinstall and it's possible that the script is waiting for user input (on a cp command or something) but the prompt asking for using input has been suppressed .

Log file itself looks fine and it seems as if rTorrent is being installed without issue. It's hanging during the configuration steps.

Similarly you can try running `bash -x /etc/swizzin/scripts/install/rtorrent.sh` which will enable debug output and should list each command the installer runs as it runs it.

**Comment by Qwatuz** [comment]
That command gives a lot better insight, it looks as if it's trying to chown my entire /home/user instead of just /home/user/{torrents,.sessions,rwatch} etc.

If that's the case, then it is trying to chown my google drive mounts.


`+ mkdir -p /home/USERNAME/torrents/rtorrent
+ mkdir -p /home/USERNAME/.sessions
+ mkdir -p /home/USERNAME/rwatch
+ chown -R USERNAME.USERNAME /home/USERNAME/torrents /home/USERNAME/.sessions /home/USERNAME/rwatch
+ usermod -a -G www-data USERNAME
+ usermod -a -G USERNAME www-data
+ echo 'Setting permissions on USERNAME ... '
Setting permissions on USERNAME ...
+ _perms
+ chown -R USERNAME.USERNAME /home/USERNAME/
`

**Comment by liaralabs** [comment]
Ok, that function is actually useless anyway, so I've removed it. Can you please test the update and let me know if you're able to complete the install now?

**Comment by Qwatuz** [comment]
I think we're inching closer to success, but not yet!

https://i.imgur.com/fuVvohe.png

rtorrent isn't visible on the left of the dashboard, and cannot access it via url: 404 Not Found.

However the service is running fine:

``` rtorrent@USER.service - rTorrent
   Loaded: loaded (/etc/systemd/system/rtorrent@.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2018-09-06 16:02:04 CEST; 17s ago
  Process: 31697 ExecStop=/usr/bin/screen -X -S rtorrent quit (code=exited, status=0/SUCCESS)
  Process: 31703 ExecStart=/usr/bin/screen -d -m -fa -S rtorrent /usr/bin/rtorrent (code=exited, status=0/SUCCESS)
  Process: 31701 ExecStartPre=/bin/rm -f /home/%I/.sessions/rtorrent.lock (code=exited, status=0/SUCCESS)
 Main PID: 31705 (screen)
   CGroup: /system.slice/system-rtorrent.slice/rtorrent@USER.service
           ├─31705 /usr/bin/SCREEN -d -m -fa -S rtorrent /usr/bin/rtorrent
           └─31706 /usr/bin/rtorrent



When I ran the newest box update, it seemed to break my Jackett which is odd "Bad Request (Invalid host)". Everything else works perfectly however!

Thanks again for taking the time.

**Comment by liaralabs** [comment]
You need to install the rutorrent package separately. It's not included in the rtorrent package. This is because you can install rutorrent or flood -- there is no default.

As for Jackett, make certain the client is up to date. The recent version required a config change to the proxy that would end up giving you this error on an older version.

**Comment by Qwatuz** [comment]
Brilliant, that was the answer! Thank you so much @liaralabs it's all working now!

If anyone runs into this regarding Jackett issues, even when trying to update via ssh using `mono` it didn't work, I simply `box remove jackett` and then installed it again and voila, it even kept my trackers!

I've missed rutorrent so much! :smiley:
