### ISSUE TITLE
Replace „Fancyindex“ with „h5ai“

### ISSUE THREAD

**Issue by revunix** [liaralabs/swizzin#126]
Hey, 

i'm looking for a how to: replace this ugly Fancyindex with the better h5ai. Is it simply possible, without destroying.

https://larsjung.de/h5ai/

Greetings,
alex

**Comment by liaralabs** [comment]
Possible? Probably. But support requests like this are not to be submitted as issues to the project. The issue tracker is for bug reports.

Your best bet is to find a how-to install h5ai on nginx and use it to merge into the project as is.
