### ISSUE TITLE
rutorrent autodl-irssi plugin not installed correctly with clean install

### ISSUE THREAD

**Issue by kennydeckers** [liaralabs/swizzin#129]
When doing a clean install and having selected the autodl and rutorrent packages it will not install the autodl-irssi rutorrent plugin correctly. The autodl-irssi plugin installations is triggered from `nginx/autodl.sh` which depends on the condition that the file `/install/.rutorrent.lock` exists. Since the list of packages are installed alphabetically (and a comes before r) this causes the plugin to not be installed.

**Comment by kennydeckers** [comment]
@liaralabs I just did a clean install of ubuntu 18.04 and ran into the same issue. Uninstalling the autodl package and then reinstalling it results in a correct installation.

**Comment by liaralabs** [comment]
Can't reproduce this. Just did a fresh install under 18.04:
```
Installing nginx
Installing rtorrent
Installing rTorrent Dependencies ... 
Building xmlrpc-c from source ... 
Building libtorrent from source ... 
Building rtorrent from source ... 
Making liara directory structure ... 
setting up rtorrent.rc ... 
Installing rutorrent
Installing autodl
```
Everything is being triggered in the correct order.

I've been noticing lately that a php-fpm restart is needed before the ruTorrent interface starts working on a fresh install. Have you considered the possibility that the plugin is installed but opcache is conflicting?
