### ISSUE TITLE
x2go issue

### ISSUE THREAD

**Issue by d2dyno** [liaralabs/swizzin#13]
When trying to connect to x2go, I encounter this issue:
![untitled](https://user-images.githubusercontent.com/2421939/29700235-8cd16b82-8928-11e7-9a9c-b7e5dff66d80.png)

**Comment by d2dyno** [comment]
Once again, removed using `box remove x2go` and reinstalled with `box install x2go` and it worked. Why are install options from a fresh install all borked?

**Comment by liaralabs** [comment]
x2golistsessions command not found usually indicates that x2go isn't actually installed -- meaning x2go didn't get installed the first time around.

I just did the x2go install on my personal server for the first time and it went off without a hitch here :confused:

**Comment by demonotaku** [comment]
I've noticed a lot of the apps don't like to be installed originally.

**Comment by liaralabs** [comment]
I think x2go's initial install oddities on Ubuntu should be fixed with cb66074b

If any other apps are behaving odd on a first install, please open a new issue :smile:

**Comment by liaralabs** [comment]
Closing as I've had no further reports of this issue -- given commit cb66074, I'm going to assume this one is solved.
