### ISSUE TITLE
Torrents in deluge 0 - bug?

### ISSUE THREAD

**Issue by USRGH** [liaralabs/swizzin#133]
Hello,
just installed swizzin to Ubuntu server 18.04. Works fine but in Panel I see 

Torrents in deluge
There are 0 torrents loaded

In Deluge have currently 88 torrents. Bug?

**Comment by liaralabs** [comment]
You can use ltconfig to change the name of the client reported to the tracker. Otherwise the version info is purely descriptive. The version is listed as .dev0 because it was built from the git source and not a tarball release package.

**Comment by liaralabs** [comment]
In the future, please open a new ticket for each item instead of editing your issue to a completely different problem.

Can you run the following command for me as root to see if it completes? Replace USERNAME with the name of the user in question:
```
user=USERNAME
sudo -u www-data bash -c "ls /home/${user}/.config/deluge/state/*.torrent|wc -l"
```

**Comment by USRGH** [comment]
Sorry for that.
it shows me:

ls: cannot access '/home/myusername/.config/deluge/state/*.torrent': Permission denied
0

**Comment by liaralabs** [comment]
You should check your permissions on the folders leading up to deluge/state. Your group should have read access (75*) for all the folders. (`.config/deluge/state/`)
