### ISSUE TITLE
Customize panel

### ISSUE THREAD

**Issue by acoolmanfromnowhere** [liaralabs/swizzin#134]
I added lidarr to my box and I wanted to update the link to the panel.

Tried adding $lidarrURL= "https://" . $_SERVER['HTTP_HOST'] . "/lidarr"; to /srv/panel/custom/custom.menu.php but on refresh it did not show the link. Is a restart needed for it to be updated.

**Comment by liaralabs** [comment]
You need to restart the php-fpm (or clear opcache) any time you modify files on the disk because the daemon caches the data.

If you're on debian 9 or ubuntu 16.04, the command is 'systemctl restart php7.0-fpm' -- ubuntu 18.04 is php7.2-fpm

**Comment by acoolmanfromnowhere** [comment]
I am on ubuntu 16.04, did a sudo systemctl restart php7.0-fpm. It's still not getting added.

**Comment by liaralabs** [comment]
This article on the QB KB should be helpful:

https://quickbox.io/knowledgebase/setting-up-and-using-a-custom-menu-in-quickbox/

You need to add a menu item to inject below the variable that sets the URL. Without referencing the variable, it will never get called.

**Comment by acoolmanfromnowhere** [comment]
Thanks Liara. It worked.

This is how the custom.menu.php now looks. 

// INSERT YOUR CUSTOM EXTERNAL or INTERNAL LINKS HERE! //
//$quickboxURL = "https://quickbox.io/donate/";//
$lidarrURL= "https://" . $_SERVER['HTTP_HOST'] . "/lidarr";
?> 



<!-- //<li><a href="<?php echo "$quickboxURL"; ?>" class="grayscale" target="_blank"><i class="fa fa-heart text-danger"></i> <span><?php echo T('DONATE'); ?></span></a$
<li><a class="grayscale" href="<?php echo "$lidarrURL"; ?>" target="_blank"><img src="img/brands/lidarr.png" class="brand-ico"> <span>Lidarr</span></a></li>
