### ISSUE TITLE
Cannot access Jackett Webinterface

### ISSUE THREAD

**Issue by Niklasmaximilian** [liaralabs/swizzin#139]
Hi, 

just figured out that Jackett Web UI is not accessible for me. 

https://www.*****.xyz/jackett/

It says:
Bad Request (Invalid host)

Anything else is running fine through nginx.

Any idea how to fix this issue?

**Comment by liaralabs** [comment]
You need to update jackett to the latest version.

If you just reinstall with box, your config will be saved and it will download the latest version.
