### ISSUE TITLE
FTP permission denied

### ISSUE THREAD

**Issue by d2dyno** [liaralabs/swizzin#14]
On a fresh install, with vsftpd installed in beginning options. Whenever I try to upload a file, create a folder etc, I get: 550 Permission denied. When I want to box, it didn't allow me to remove vsftpd as a package, but it did allow me to install it again.

Using Filezilla as the FTP client. I can create files/directories using SSH.

**Comment by liaralabs** [comment]
Alright - I wasn't actually pushing a default vsftpd.conf but I am now. This should tackle the issue of not being able to write. I also took the liberty of enabling ftp(s) at the same time and fixing the "vsftpd package not installed" issue

**Comment by d2dyno** [comment]
This fixed my issue. Thanks!
