### ISSUE TITLE
Create a discord server for swizzin

### ISSUE THREAD

**Issue by ooohhh** [liaralabs/swizzin#143]
Not really related to the repo, but a discord server is much easier to use than IRC (imo) and it's history and search capabilities are awesome.

**Comment by liaralabs** [comment]
Use an IRC bouncer if you want to join the IRC and are worried about missing messages. There are three included in swizzin (The Lounge, Quassel and ZNC). Unfortunately, I don't have time to maintain any more forms of community communication.

Further, Discord is not open source and I would prefer to continue supporting open source projects.
