### ISSUE TITLE
Downgrade to rtorrent 0.9.6

### ISSUE THREAD

**Issue by amlopin** [liaralabs/swizzin#150]
Hi, how can I downgrade rtorrent to version 0.9.6? Thanks :D

**Comment by amlopin** [comment]
Fixed it

**Comment by Wyall** [comment]
You could become MVP if you'd actually write how you solved/did it for other people

**Comment by amlopin** [comment]
You are right, I forgot to tell. I run the script and voilá! was asking me the option to choose version. :D
