### ISSUE TITLE
htpasswd Install Issue

### ISSUE THREAD

**Issue by Ed-Alderson** [liaralabs/swizzin#151]
I'm installing on a fresh copy of Debian 9.4 and I ran into an interesting issue when using the install script. Choices made in the installer prompts are for nginx, deluge, and panel. After the installer script prints "Creating new user [Insert Username here] ... ", I end up seeing the help dialog for htpasswd printed twice. I'm assuming at this point that the only reason that was printed is because the htpasswd commands from the script weren't quite right.

The installer script then moves onto installing nginx which seems to go fine as I only see "Installing nginx" printed. The script then moves onto installing deluge and I see "cat: /etc/htpasswd: No such file or directory" printed in the terminal. ~~At this point the installer seems to pause/hang and nothing happens after.~~

The installer finally finished, but I end up seeing the following errors printed for deluge:
`cat: /home/rei_1/.config/deluge/core.conf: No such file or directory`
`Your deluge daemon port is`
`cat: /home/rei_1/.config/deluge/web.conf: No such file or directory`
`Your deluge web port is`

After rebooting, trying to access the panel and entering the credentials for the user created through the installer just kicks me over to a 403 error page from Nginx.

So is this an issue with Swizin or with Debian?

<img width="602" alt="swizin install issue" src="https://user-images.githubusercontent.com/43834810/46448480-bdaf5500-c722-11e8-9f4c-a2c0e0f2bbbf.png">

**Comment by liaralabs** [comment]
This might be an issue with the username you've chosen. Usernames should be alphanumeric without any other symbols or uppercase characters

**Comment by Ed-Alderson** [comment]
> This might be an issue with the username you've chosen. Usernames should be alphanumeric without any other symbols or uppercase characters

So I did a fresh install on Debian 9.5 and chose a username that's all lowercase and alphanumeric this time around, and I still ran into the same errors and issues as above.

**Comment by liaralabs** [comment]
Are you using the same password as before? Do you have any special
characters in it? Perhaps a single quote or maybe a backslash?

**Comment by Ed-Alderson** [comment]
> Are you using the same password as before? Do you have any special characters in it? Perhaps a single quote or maybe a backslash? Edit: or a space for that matter

Ah, that appears to have been the problem. Thanks for the help in troubleshooting!

**Comment by liaralabs** [comment]
Can you tell me which character it ended up being? I'd like to run some
tests to see if I can make the variables a bit more resilient.

**Comment by Ed-Alderson** [comment]
> Can you tell me which character it ended up being? I'd like to run some tests to see if I can make the variables a bit more resilient.
> […](#)

It was a space between words in the password.
