### ISSUE TITLE
Remove http auth

### ISSUE THREAD

**Issue by rsmsha** [liaralabs/swizzin#153]
Hi, I'm trying to remove HTTP auth for the deluge page, because I want to setup radarr/sonarr from my local server to my seedbox and I can't because of the authentication. I've tried with various settings on /etc/nginx/apps/deluge.conf but I can't get it to work. I don't know if this is the right place, but I've seen other people with the same problem and I hope I might find a way here.
Thanks.

**Comment by liaralabs** [comment]
You would need to remove the $remote_user variable from the config and define it manually. You'll be unable to use this setup with multiple users if you do so though.

 ```
root@srv:~# cat /etc/nginx/conf.d/liara.deluge.conf 
upstream liara.deluge {
  server 127.0.0.1:10498;
}
```
And
```
root@srv2393:~# cat /etc/nginx/apps/deluge.conf 
location /deluge {
  return 301 /deluge/;
}

location /deluge/ {
  include /etc/nginx/snippets/proxy.conf;
  auth_basic "What's the password?";
  auth_basic_user_file /etc/htpasswd;
  proxy_set_header X-Deluge-Base "/deluge/";
  rewrite ^/deluge/(.*) /$1 break;
  proxy_pass http://$remote_user.deluge;
}
```

Change $remote_user to your username or change the whole proxypass to the upstream server defined in the file in conf.d. You may need to remove the rewrite variable as it's often needed for variables in the proxy_pass line, but if you remove it, the rewrite should become un-needed.

**Comment by rsmsha** [comment]
Thanks!
