### ISSUE TITLE
Nextcloud Missing PHP Files

### ISSUE THREAD

**Issue by kanenses** [liaralabs/swizzin#16]
Hello,

Nextcloud missing the follow components for working:

    No database drivers (sqlite, mysql, or postgresql) installed.
    PHP module zip not installed.

    Please ask your server administrator to install the module.
    PHP module mb multibyte not installed.

    Please ask your server administrator to install the module.
    PHP module GD not installed.

    Please ask your server administrator to install the module.
    PHP modules have been installed, but they are still listed as missing?

    Please ask your server administrator to restart the web server.

**Comment by liaralabs** [comment]
Server was facing some unrelated mysql errors
