### ISSUE TITLE
OMBI doesn't launch 

### ISSUE THREAD

**Issue by kiboyazetsubou** [liaralabs/swizzin#160]
Ombi crashes and does not activate 
ubuntu 18.04

**Comment by GiowGiow** [comment]
For me I had to chmod /opt/Ombi so it could run properly

**Comment by liaralabs** [comment]
Are you running a fresh install or an old version? There was an update to Ombi that I pushed a while ago, which addressed the permission issues that arose out of the changes in the Repo. /opt/Ombi should be owned by root: and /etc/Ombi should be owned by the ombi user -- this is where ombi will store client data and it will no longer store it in the /opt directory.

**Comment by kiboyazetsubou** [comment]
Brand New Install
setting /opt/ombi to <user>:<user> fixed the issue

**Comment by liaralabs** [comment]
I just pushed the proper fix to the repo. If you're having issues, you can just `box update` as the update script already contained the proper fix.
