### ISSUE TITLE
Switch Deluge dev install to 2.0 branch

### ISSUE THREAD

**Issue by d2dyno** [liaralabs/swizzin#161]
Beta 2.0 is out, and in the develop PPA. Should swizzin switch to it?
https://forum.deluge-torrent.org/viewtopic.php?t=54338
https://launchpad.net/~deluge-team/+archive/ubuntu/develop/

**Comment by khnielsen** [comment]
Rather old one here, from my testings 2.0 is not stable yet as a replacement, there's some good progress and stability might have changed since I tested it about 1 month ago, personally I would avoid it on a dev install, then it should get its own dev2.0 branch or similar for those that want it.
