### ISSUE TITLE
Tautulli is created with own user

### ISSUE THREAD

**Issue by herrwusel** [liaralabs/swizzin#163]
So when tautulli is installed with the box command, it is added with its own user which can result in some error when you want to use the script functionality.

**Comment by liaralabs** [comment]
This is intentional and is for security purposes. If you need your client to run other user's scripts or access their files, look into groups/group permissions to bypass this.

**Comment by herrwusel** [comment]
Thanks for clarifying. Hijacking this issue for another question: is it also wanted that tautulli isn't http authentication protected like the other accessible web interfaces?

**Comment by liaralabs** [comment]
Users requested that it be removed because I think it interferes with the
mobile applications. You can enable the built in authentication that should
be compatible if you want it.
