### ISSUE TITLE
Tautulli - Missing

### ISSUE THREAD

**Issue by nebb00** [liaralabs/swizzin#165]
Hi All

Tautulli is not working for me. I installed during the initial deployment, but when going to use it, I noticed its not accessible via the panel.

when I try removing and installing again. I get the following;
```
root@nebbflix / # box remove tautulli
Removing tautulli
bash: /usr/local/bin/swizzin/remove/tautulli.sh: No such file or directory
root@nebbflix / # box install tautulli
Package tautulli already installed
```

When I look at the logs. I see the web server has started but is inaccessible.
```
MainThread : Tautulli WebStart :: Starting Tautulli web server on http://127.0.0.1:8181/tautulli/
```

**Comment by cyberundertaker** [comment]
same thing here. didn't find any solution yet

**Comment by liaralabs** [comment]
The panel hasn't been updated to reflect the recent changes yet; however you can still access it via the endpoint /tautulli (you can also use /plexpy, which will redirect). I've just pushed a rename of the script that will allow you to remove it with box.
