### ISSUE TITLE
Box upgrade plex not working?

### ISSUE THREAD

**Issue by LaMpiR** [liaralabs/swizzin#166]
Hi.

I can't upgrade plex from the command box upgrade plex.

root@xxx:~# box upgrade plex
Updating swizzin local repository
M       scripts/install/wireguard.sh
M       scripts/remove/wireguard.sh
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 3032ccf Once more...
Already up to date.
Updating panel
From https://github.com/liaralabs/quickbox_dashboard
 * branch            master     -> FETCH_HEAD
Already up to date.
HEAD is now at 65f8719 updated css aesthetics to address overlapping
Already up to date.
root@xxx:~#

**Comment by liaralabs** [comment]
Fixed with f5e9ac01cd2723acbb96f730871dd3abed5f1d3b

**Comment by liaralabs** [comment]
Are the panel and netdata configs present in /etc/nginx/apps? The nginx
upgrade command is the more likely culprit, but that would be a different
issue from this.

**Comment by Tapol** [comment]
In /etc/nginx/apps I have only one file, this is shell.conf.

**Comment by liaralabs** [comment]
What locks exist in your /install folder? (`ls -la /install`) The upgrade script uses these lock files to trigger the nginx scripts for the applications (https://github.com/liaralabs/swizzin/blob/master/scripts/upgrade/nginx.sh#L48-L54)

**Comment by Tapol** [comment]
I have this locks:

-rw-r--r--  1 root root    0 Nov 14 01:48 .ffmpeg.lock                                                                                   
-rw-r--r--  1 root root    0 Nov 15 22:29 .netdata.lock                                                                                  
-rw-r--r--  1 root root    0 Nov 14 01:38 .nginx.lock                                                                                    
-rw-r--r--  1 root root    0 Nov 14 01:46 .panel.lock                                                                                    
-rw-r--r--  1 root root    0 Nov 14 01:46 .rtorrent.lock                                                                                 
-rw-r--r--  1 root root    0 Dec  5 04:38 .rutorrent.lock                                                                                
-rw-r--r--  1 root root    0 Nov 14 01:50 .shellinabox.lock                                                                              
-rw-r--r--  1 root root    0 Nov 14 01:47 .vsftpd.lock

**Comment by Evoley** [comment]
I seem to be having the same problem with box not upgrading emby.

**Comment by LaMpiR** [comment]
Still not upgrading :) Any news?

**Comment by 2wenty2wo** [comment]
As with LampiR, I also can't update Plex, I get the same output with it saying "Upgrading Plex".
