### ISSUE TITLE
 7076] Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by D3monCoder** [liaralabs/swizzin#167]
I got this error on rutorrent. This happens after installing some plugins from rtx and adding some new themes. seems like a permission issue of plugin and themes files and folder. a command to fix permission to both themes and plugins folder will be able to solve this i belive

**Comment by liaralabs** [comment]
JS errors are relatively common with ruTorrent, especially using the git head. I haven't found them to actually impact the usage of the client however. Regardless, such errors would be better reported to the dev, as I'm fairly certain there are no permission errors when installing the themes. (rtx will chown the plugin directory as www-data after each operation)
