### ISSUE TITLE
Problem certi SSL

### ISSUE THREAD

**Issue by Cyril5900** [liaralabs/swizzin#168]
Hello,

I have a problem during the installation I have an error on let's encrypt I have the following error have you an idea of the problem? ubuntu 16 installation brand new.

What information do you need?

Thank you in advance

[jeudi 6 décembre 2018, 16:25:08 (UTC+0100)] Check the nginx conf before setting up.
[jeudi 6 décembre 2018, 16:25:08 (UTC+0100)] OK, Set up nginx config file
[jeudi 6 décembre 2018, 16:25:08 (UTC+0100)] nginx conf is done, let's check it again.
[jeudi 6 décembre 2018, 16:25:08 (UTC+0100)] Reload nginx
[jeudi 6 décembre 2018, 16:25:14 (UTC+0100)] www.my-domain.ovh:Verify error:Invalid response from http://www.my-domain.ovh/.well-known/acme-challenge/cOUFfwwBZoxENQdnTcczZX5bkNhzHWS6Ejku8WHcMA4:
[jeudi 6 décembre 2018, 16:25:14 (UTC+0100)] Restoring from /root/.acme.sh/www.my-domain.ovh/backup/www.XXXXX.ovh.nginx.conf to /etc/nginx/sites-enabled/default
[jeudi 6 décembre 2018, 16:25:14 (UTC+0100)] Reload nginx
[jeudi 6 décembre 2018, 16:25:14 (UTC+0100)] Please add '--debug' or '--log' to check more details.
[jeudi 6 décembre 2018, 16:25:14 (UTC+0100)] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
ERROR: Certificate could not be issued. Please check your info and try again
N:/home/XXXXX# acme.sh --force --issue -d mbdnet.net -w ~/www --dns dns_gd
[jeudi 6 décembre 2018, 16:28:20 (UTC+0100)] Creating domain key
[jeudi 6 décembre 2018, 16:28:21 (UTC+0100)] The domain key is here: /root/.acme.sh/mbdnet.net/mbdnet.net.key
[jeudi 6 décembre 2018, 16:28:21 (UTC+0100)] Single domain='mbdnet.net'
[jeudi 6 décembre 2018, 16:28:21 (UTC+0100)] Getting domain auth token for each domain
[jeudi 6 décembre 2018, 16:28:21 (UTC+0100)] Getting webroot for domain='mbdnet.net'
[jeudi 6 décembre 2018, 16:28:21 (UTC+0100)] Getting new-authz for domain='mbdnet.net'
[jeudi 6 décembre 2018, 16:28:22 (UTC+0100)] The new-authz request is ok.
[jeudi 6 décembre 2018, 16:28:22 (UTC+0100)] Verifying:mbdnet.net
[jeudi 6 décembre 2018, 16:28:25 (UTC+0100)] mbdnet.net:Verify error:Invalid response from http://mbdnet.net/.well-known/acme-challenge/VLQq9Qsk26xlpMVrNnBbJFjfCVKJKbv3huGt3AR5Buo:
[jeudi 6 décembre 2018, 16:28:25 (UTC+0100)] Please add '--debug' or '--log' to check more details.
[jeudi 6 décembre 2018, 16:28:25 (UTC+0100)] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
/home/# acme.sh --force --issue -d my-domain.ovh -w ~/www --dns dns_gd
[jeudi 6 décembre 2018, 16:28:44 (UTC+0100)] Single domain='my-domain.ovh'
[jeudi 6 décembre 2018, 16:28:44 (UTC+0100)] Getting domain auth token for each domain
[jeudi 6 décembre 2018, 16:28:44 (UTC+0100)] Getting webroot for domain='my-domain.ovh'
[jeudi 6 décembre 2018, 16:28:44 (UTC+0100)] Getting new-authz for domain='my-domain.ovh'
[jeudi 6 décembre 2018, 16:28:45 (UTC+0100)] The new-authz request is ok.
[jeudi 6 décembre 2018, 16:28:45 (UTC+0100)] Verifying:my-domain
[jeudi 6 décembre 2018, 16:28:49 (UTC+0100)] my-domain.ovh:Verify error:Invalid response from http:///.well-known/acme-challenge/mvbmrOfaAsG6gG2bdBIiaizAE6zTf6v05kRRnGTIHhU:
[jeudi 6 décembre 2018, 16:28:49 (UTC+0100)] Please add '--debug' or '--log' to check more details.
[jeudi 6 décembre 2018, 16:28:49 (UTC+0100)] See: https://github.com/Neilpang/acme.sh/wiki/How-to-debug-acme.sh
 ~/.acme.sh/acme.sh --deploy -d my-domain.ovh --deploy-hook cpanel_uapi

**Comment by khnielsen** [comment]
You have not posted the entire log here, but it looks like you are trying to hookup to a domain that are not valid and therefore it will fail to sign it.
