### ISSUE TITLE
Sonarr/Radarr upgrade

### ISSUE THREAD

**Issue by swizzinboy** [liaralabs/swizzin#169]
Hi! I would like to ask how can I upgrade swizzin or single modules? 

Do I have to change the ownership, run the update command for each module and then change it back? It does not work without root through the GUI. 

Are there any command examples or steps that needs to be taken. Box upgrade is not present for all modules like e.g. Sonarr and Radarr.

Also Plex is not being updated (its server side). I run the upgrade script but it does nothing.

It would be good to add it to the Wiki if possible.

Thank you.

**Comment by Erfie** [comment]
I have the same problem with plex not being updated.

> root@x:# box update
> Updating swizzin local repository
> M       scripts/install/wireguard.sh
> M       scripts/remove/tautulli.sh
> M       scripts/remove/wireguard.sh
> Already on 'master'
> Your branch is up-to-date with 'origin/master'.
> HEAD is now at 0e39c55 Fix debian gpg key for x2go repository
> Already up-to-date.
> HEAD is now at 65f8719 updated css aesthetics to address overlapping
> Already up-to-date.
> root@x:# box upgrade plex
> Updating swizzin local repository
> M       scripts/install/wireguard.sh
> M       scripts/remove/tautulli.sh
> M       scripts/remove/wireguard.sh
> Already on 'master'
> Your branch is up-to-date with 'origin/master'.
> HEAD is now at 0e39c55 Fix debian gpg key for x2go repository
> Already up-to-date.
> HEAD is now at 65f8719 updated css aesthetics to address overlapping
> Already up-to-date.
> Upgrading plex

**Comment by Drastiques** [comment]
i think i kinda """found""" the solution to these issues
i executed myself the update script for emby ( emby.sh) and i removed the part where the output is directed to /dev/null 
and this is what i got :
 ```
 ./emby.sh
(Reading database ... 55745 files and directories currently installed.)
Preparing to unpack emby.dpkg ...
Unpacking emby-server (3.5.2.0) over (3.5.2.0) ...
Setting up emby-server (3.5.2.0) ...

Configuration file '/etc/emby-server.conf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
```

so then, what i did is when the script was stuck on upgrading emby, i'd press Y then enter 
so that it installs but that's only a workaround

**Comment by drunkrx** [comment]
> Are there any command examples or steps that needs to be taken. Box upgrade is not present for all modules like e.g. Sonarr and Radarr.

To update Sonarr and Radarr, in both web GUI's, goto to Settings -> General -> Update (at bottom of page) and change master to develop. Then click Save. 

Cheers!
