### ISSUE TITLE
Rutorrent throttle issue

### ISSUE THREAD

**Issue by d2dyno** [liaralabs/swizzin#17]
I know liara hates the throttle plugin for rutorrent, but I have need of it. I tried loading the plugin myself, setting permissions, but for some reason, rutorrent always just says it failed to load the throttle plugin. Can we bring this plugin back, or at least the option to add additional plugins?

Also, was gonna bring this up in IRC, but I can't seem to get into the server. Just constant connect/disconnect loop.

**Comment by liaralabs** [comment]
I'm thinking about a plugin hook for box, but I'm not sure at the moment if I want to go down that point or not, I don't really want to go the route of storing all the plugins locally in the repo though and I don't really want to write individual scripts for each plugin.

However, you're right in my hatred of the throttle plugin :smile:

When the installer runs, there is no special command to ensure the complete and utter destruction of throttle from now until forever on your server :wink: Just clear opcache with either `systemctl restart php7.0-fpm` or more gracefully with `php-fpm-cli -r 'opcache_reset();'`

IRC is up without issues - are you using port 6697? Ensure ssl is checked.

**Comment by liaralabs** [comment]
This info is now in the wiki
