### ISSUE TITLE
Deluge complete removal

### ISSUE THREAD

**Issue by forsomefun2** [liaralabs/swizzin#171]
I think there an issue with some of the removal scripts. Which can relay break your sever if you don't know what your doing which I hardly do. 
1. This occurs when trying to remove deluge with swizzin, and trying to install manually or with swizzin again. 

Anyways
At some points 
deluge==1.3.15' distribution was not found 

It seems the way to fix this issue is to 
sudo apt-get --purge remove deluge-common deluge deluge-console deluge-gtk deluge-torrent deluge-web deluge-webui deluged libtorrent-rasterbar9"

then
sudo apt-get install deluge-common deluge deluge-console deluge-gtk deluge-torrent deluge-web deluge-webui deluged libtorrent-rasterbar6" and still same error

Secondly there is a second bug where you can setup remote access with this guide
https://dev.deluge-torrent.org/wiki/UserGuide/ThinClient 

but remote access will never work. Other then the webui

Fix for this seems to be 
removing the two deluge and deluged folders in 
/usr/lib/python2.7/dist-packages 
I notice that every time I entered my password into deluged for windows it was calling this folder, but was saying the remote password was wrong. 

After that you can

sudo apt-get install  deluged deluge-console deluge-gtk deluge-torrent deluge-web deluge-webui deluged libtorrent-rasterbar9

**Comment by garikaib** [comment]
I can confirm this. Infact removing deluge using the box command will mean you having to roll your sleeve to get it back. Reinstalling wont work at all.

**Comment by liaralabs** [comment]
@garikaib just chiming in with a +1 is not enough considering the deluge scripts have been massively refactored recently.

I need more info:

OS
Deluge version chosen
Libtorrent version chosen

**Comment by garikaib** [comment]
Debian baster (10)
Repo
Repo

**Comment by forsomefun2** [comment]
Deluge is very messy it seems
Had an install that reverse to work.

I think it important to stop app services before purging. Remove the config folder and install with swizzin or follow the steps from thin/client setup.

Also maybe check the install from source after uninstalling to see if any files are left over. 
Clear out browser cache
