### ISSUE TITLE
downgrade to 0.9.6/0.13.6

### ISSUE THREAD

**Issue by Lucif3r-MorningSter** [liaralabs/swizzin#175]
the latest rtorrent has peer handling issues in many trackers.  please make a way to downgrade

**Comment by liaralabs** [comment]
rTorrent 0.9.6 is only supported on Debian Jessie or Ubuntu 16.04. If you are running either of these OSs, you can `box upgrade rtorrent`  to re-run the compilation and install whichever supported version you care to.

On Debian 9 and Ubuntu 18.04 and later, if you really need to, compiling 0.9.6 can be done with a patch to libtorrent (which is in `swizzin/sources/openssl.patch`). There are no instructions to do so and this is not supported. If you really need instructions, google around to find how to apply a patch file.
