### ISSUE TITLE
Tautulli fails upon install

### ISSUE THREAD

**Issue by RikT** [liaralabs/swizzin#180]
OS:Debian stretch
upon install of Tautulli it fails at time it has to start here are the logs;

`root@vps634319:~# box install tautulli
Installing tautulli
Enabling Tautulli Systemd configuration
Job for tautulli.service failed because the control process exited with error code.
See "systemctl status tautulli.service" and "journalctl -xe" for details.
----------------------------------------------------------------------------------

-- Unit tautulli.service has begun starting up.
Jan 23 20:18:00 vps634319 Tautulli.py[7872]: Traceback (most recent call last):
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:   File "/opt/tautulli/Tautulli.py", line 38, in <module>
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:     import plexpy
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:   File "/opt/tautulli/plexpy/__init__.py", line 37, in <module>
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:     import activity_handler
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:   File "/opt/tautulli/plexpy/activity_handler.py", line 24, in <module>
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:     import activity_processor
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:   File "/opt/tautulli/plexpy/activity_processor.py", line 21, in <module>
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:     import database
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:   File "/opt/tautulli/plexpy/database.py", line 24, in <module>
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:     import logger
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:   File "/opt/tautulli/plexpy/logger.py", line 30, in <module>
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:     import helpers
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:   File "/opt/tautulli/plexpy/helpers.py", line 48, in <module>
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:     from plexpy.api2 import API2
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:   File "/opt/tautulli/plexpy/api2.py", line 39, in <module>
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:     import notification_handler
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:   File "/opt/tautulli/plexpy/notification_handler.py", line 43, in <module>
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:     from newsletter_handler import notify as notify_newsletter
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:   File "/opt/tautulli/plexpy/newsletter_handler.py", line 29, in <module>
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:     NEWSLETTER_SCHED = BackgroundScheduler()
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:   File "/opt/tautulli/lib/apscheduler/schedulers/base.py", line 82, in __init__
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:     self.configure(gconfig, **options)
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:   File "/opt/tautulli/lib/apscheduler/schedulers/base.py", line 121, in configure
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:     self._configure(config)
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:   File "/opt/tautulli/lib/apscheduler/schedulers/background.py", line 29, in _configure
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:     super(BackgroundScheduler, self)._configure(config)
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:   File "/opt/tautulli/lib/apscheduler/schedulers/base.py", line 689, in _configure
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:     self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:   File "/opt/tautulli/lib/tzlocal/unix.py", line 131, in get_localzone
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:     _cache_tz = _get_localzone()
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:   File "/opt/tautulli/lib/tzlocal/unix.py", line 70, in _get_localzone
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:     return pytz.timezone(etctz.replace(' ', '_'))
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:   File "/opt/tautulli/lib/pytz/__init__.py", line 178, in timezone
Jan 23 20:18:00 vps634319 Tautulli.py[7872]:     raise UnknownTimeZoneError(zone)
Jan 23 20:18:00 vps634319 Tautulli.py[7872]: pytz.exceptions.UnknownTimeZoneError: ''
Jan 23 20:18:00 vps634319 systemd[1]: tautulli.service: Control process exited, code=exited status=1
Jan 23 20:18:00 vps634319 systemd[1]: Failed to start Tautulli - Stats for Plex Media Server usage.
-- Subject: Unit tautulli.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit tautulli.service has failed.
`

**Comment by liaralabs** [comment]
Python depends may not have been installed, especially if you haven't installed another python application such as Deluge. This should be fixed in the latest commit (85d5d47310286ea4159fbd89442fc0d21e24d95a)
