### ISSUE TITLE
EBMY Upgrade 3.5.2.0 -> 4.0.1.0

### ISSUE THREAD

**Issue by Coradol** [liaralabs/swizzin#181]
Please upgrade Emby from 3.5.2.0 to actul version 4.0.1.0. Thanks!

**Comment by shinji257** [comment]
The current emby upgrade script actually checked emby's github which is still at 3.5.2.0 for some reason.  However the website does indicate 4.0.1.0.

**Comment by Evoley** [comment]
@shinji257 Emby went closed sourced. That's why the github hasn't been updated. I'm not exactly sure if @liaralabs is going to fix it or just leave it as it is. There is an alternative called Jellyfin if you guys are interested. It's based on Emby 3.5.2.0 and is showing some promise.

**Comment by liaralabs** [comment]
Yes, sadly it is true that Emby has gone closed-source.

I've updated the installer and upgrade script to prefer version information scraped from Emby.Releases rather than Emby, as there are no more open-source versions being released of this software.
