### ISSUE TITLE
TheLounge V3 Theme Install Issue

### ISSUE THREAD

**Issue by theoneandonlyewok** [liaralabs/swizzin#184]
Everything is functioning aside from the theme stuff as far as I can tell. 

Noticed that Zenburn wasn't there any longer with the new V3 install. Tried to install it manually via:

thelounge install thelounge-theme-zenburn

and it outputs this error
`2019-02-12 18:01:37 [ERROR] /root/.thelounge/config.js does not exist.`

Tried it with a few other themes and it gives the same error.

Not sure if it's related to the following which changed with V3 as well:
`  Environment variable:

    THELOUNGE_HOME   Path for all configuration files and folders. Defaults to /root/.thelounge.`

`The environment variable $LOUNGE_HOME that can be used to point The Lounge to a specific home directory (housing configuration file, packages, user settings, etc.) is now called $THELOUNGE_HOME. More details here.`

`The --home option has been removed. Use the $THELOUNGE_HOME environment variable instead.`

**Comment by liaralabs** [comment]
The lounge isn't installed as the root user, it's installed under `lounge`. See (here)[https://github.com/liaralabs/swizzin/blob/master/scripts/install/lounge.sh#L17] for inspiration on how to properly structure a command.
