### ISSUE TITLE
letsencrypt installation suggestion

### ISSUE THREAD

**Issue by Autotonic** [liaralabs/swizzin#189]
remove `/root/.acme.sh/` if it exists when running `letsencrypt.sh` install.

**Comment by liaralabs** [comment]
What is the reasoning behind this?

The installer checks for acme and installs it if it's not found. I don't see the point in removing it if it's currently on the server.

**Comment by Autotonic** [comment]
In my case when moving name servers and setting up cloudflare; the existing info in .acme.sh/ prevented the installation from succeeding.

**Comment by liaralabs** [comment]
Deleting the .acme folder will have the side-effect of deleting all profiles that are currently setup, however. So, if this isn't the first time you're running letsencrypt, you'll also remove the renewal profiles you already have setup for the other domains on your server.

Unfortunately, as a result, what you're suggesting is not a good idea. I believe the best alternative would be to delete the acme folder only if something is wrong and you need to reset the configuration on your server, not as default behavior each and every time the script is run.
