### ISSUE TITLE
Problems with rtorrent installation

### ISSUE THREAD

**Issue by BlayZin** [liaralabs/swizzin#191]
rtorrent installation doesn't seem to work at all.
I tried 2 fresh installs and I only ran those commands:

```
apt update && apt upgrade -y
bash <(wget -O- -q  https://raw.githubusercontent.com/liaralabs/swizzin/master/setup.sh) (I chose only nginx)
reboot
box install rtorrent rutorrent panel
```

when creating the /tmp/.install.lock and trying to reinstall rtorrent I get to this point:
```
configure: error: Package requirements (libtorrent >= 0.13.7) were not met:

No package 'libtorrent' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables DEPENDENCIES_CFLAGS
and DEPENDENCIES_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
Created symlink /etc/systemd/system/multi-user.target.wants/rtorrent@blayzin.service → /etc/systemd/system/rtorrent@.service.
```

**Comment by liaralabs** [comment]
What OS?

What about logging details pulled from /root/logs/install.log

**Comment by BlayZin** [comment]
ok sorry forgot to mention I use Ubuntu 18.04 lts
[install.log](https://github.com/liaralabs/swizzin/files/2994177/install.log)

**Comment by liaralabs** [comment]
According to the logs you sent over, it looks like there's an issue with the last commit from libtorrent feature-bind.

This issue seems to cover the error:

https://github.com/rakshasa/libtorrent/issues/186

Libtorrent should build if you checkout libtorrent and rtorrent at the commit right before the introduction of the ai_* commit.

I just rebuilt the package on Debian 9 last night, so I know the package is working there. It may be the newer packages in 18.04 causing a conflict.

I will wait and see a bit before committing a change, as this should probably be fixed upstream

**Comment by BlayZin** [comment]
Ok thanks for looking into it. I guess I'll wait then.

**Comment by kalanihelekunihi** [comment]
I can also confirm that installing using the following commit IDs works fine under Ubuntu 18.04
libtorrent : 685fdb238e5ad0cb80df12f8954ed6ed78de04a3
rtorrent : e919f08b9095f5761812013e32990a33a470a8e7

But, if you are doing a fresh install, it'll let you get up and running.

**Comment by liaralabs** [comment]
I've re-enabled the option to build the old-stable/new-unstable tarballs for Debian 9 and Ubuntu 18.04. You can use either of these options until the feature-bind branch becomes stable for building again under 18.04.

Don't forget `box upgrade rtorrent` can be used to change an existing install (if you want to move to feature-bind in the future when this commit is fixed)

**Comment by BlayZin** [comment]
Thanks for the change.
But now I run into a different problem.
The indicator in the panel also doesn't show if it is running or not it's just always green no matter what.
Not that it is a big problem but still wanted to report.
