### ISSUE TITLE
Ombi broken on reinstall

### ISSUE THREAD

**Issue by theoneandonlyewok** [liaralabs/swizzin#194]
Had ombi installed on the first initial install. it was having some weird database issues so I uninstalled via "box remove ombi", restarted the server, and did another "box install ombi"

Box reported the install was fine, but Ombi is inaccessible.

Ping the status of the service from systemctl and got this error:
```
● ombi.service - Ombi - PMS Requests System
   Loaded: loaded (/etc/systemd/system/ombi.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sun 2019-03-24 20:39:20 EDT; 1s ago
  Process: 3281 ExecStart=/opt/Ombi/Ombi --baseurl /ombi --host http://127.0.0.1:3000 --storage /etc/Ombi (code=exited, status=200/CHDIR)
 Main PID: 3281 (code=exited, status=200/CHDIR)
```

**Comment by liaralabs** [comment]
Ombi wasn't properly being uninstalled. If you currently have the ombi package installed, update and then remove the package. Reinstall should work.

If the package isn't installed, run `apt remove ombi` and then reinstall the package again.
