### ISSUE TITLE
TheLounge fails to connect to any IRC server after installation

### ISSUE THREAD

**Issue by georgyorgy1** [liaralabs/swizzin#196]
I installed TheLounge using box and I can't connect to any IRC servers.

```
10:57 Network created, connecting to irc.swizzin.ltd:6697...
10:57 Connection closed unexpectedly: Error: connect EINVAL 195.201.24.109:6697 - Local (127.0.0.1:43654)
10:57 Disconnected from the network, and will not reconnect. Use /connect to reconnect again.
```

I can provide more info if required but I don't exactly know where the log file is. 

Thanks!

**Comment by liaralabs** [comment]
6697 is the SSL port -- did you check that SSL is enabled?

Otherwise, do you have a firewall or csf enabled on the server?

**Comment by georgyorgy1** [comment]
SSL is enabled. I even tried connecting to a non-SSL port and the SSL and Use Trusted Certificates  unchecked and that didn't work either. The firewall isn't causing any problems. I had ZNC before and was able to connect to SSL ports without any problems. I'll double check the firewall when I get the chance to SSH to my server.

**Comment by georgyorgy1** [comment]
I found a way to fix this. In the configuration file (config.js), set `bind` from "127.0.0.1" to undefined.
