### ISSUE TITLE
Issues with Debian 9.1

### ISSUE THREAD

**Issue by cyrilpawelko** [liaralabs/swizzin#20]
Hello,

Fresh install on a fresh VPS running Debian 9.1 
- Install script should stop if nginx is not installed
- Warning regarding socat, should be installed before (or die) :
```
[Wed Sep 20 22:06:44 CEST 2017] Installing from online archive.
[Wed Sep 20 22:06:44 CEST 2017] Downloading https://github.com/Neilpang/acme.sh/archive/master.tar.gz
[Wed Sep 20 22:06:45 CEST 2017] Extracting master.tar.gz
[Wed Sep 20 22:06:45 CEST 2017] It is recommended to install socat first.
[Wed Sep 20 22:06:45 CEST 2017] We use socat for standalone server if you use standalone mode.
[Wed Sep 20 22:06:45 CEST 2017] If you don't use standalone mode, just ignore this warning.

```
These aren't big issues, but the installation could be smoother.

Best regards

**Comment by liaralabs** [comment]
> Install script should stop if nginx is not installed

Great point, thanks! I will make sure there is a check for this.

> Warning regarding socat

This is only for standalone mode:
```
[Wed Sep 20 22:06:45 CEST 2017] We use socat for standalone server if you use standalone mode.
[Wed Sep 20 22:06:45 CEST 2017] If you don't use standalone mode, just ignore this warning.
```

We do not use standalone mode, thus this warning should be ignored. I try not to install dependencies which are not necessary to help keep the installation as light as possible. The LE script still functions perfectly without the presence of socat.
