### ISSUE TITLE
Long-time user unable to install on new server -

### ISSUE THREAD

**Issue by tmm22** [liaralabs/swizzin#204]
Hi long-time user unable to install a new server. The usual wizard pops up asked me questions. I run through is normal and I get all these error messages after the install and a forbidden message when I try to load in my web browser . Any help would be greatly appreciated. Kind regards, Paul -s https://raw.githubusercontent.com/liaralabs/swizzin/master/setup.sh)
Checking OS version and release ...
I have determined you are using Ubuntu 18.04.
Updating system and grabbing core dependencies.
Checking enabled repos
Cloning swizzin repo to localhost
ln: failed to create symbolic link '/usr/local/bin/swizzin': File exists
chmod: cannot access '/etc/swizzin/scripts': No such file or directory
cp: cannot stat '/etc/swizzin/sources/skel': No such file or directory
Creating new user my ...
/dev/fd/63: line 149: htpasswd: command not found
/dev/fd/63: line 151: htpasswd: command not found
find: ‘/usr/local/bin/swizzin/install’: No such file or directory
Installing nginx
bash: /usr/local/bin/swizzin/install/nginx.sh: No such file or directory
Installing rtorrent
bash: /usr/local/bin/swizzin/install/rtorrent.sh: No such file or directory
Installing rutorrent
bash: /usr/local/bin/swizzin/install/rutorrent.sh: No such file or directory
Installing deluge
bash: /usr/local/bin/swizzin/install/deluge.sh: No such file or directory
Installing autodl
bash: /usr/local/bin/swizzin/install/autodl.sh: No such file or directory
Installing panel
bash: /usr/local/bin/swizzin/install/panel.sh: No such file or directory
Installing vsftpd
bash: /usr/local/bin/s

**Comment by liaralabs** [comment]
Was there possibly another instance of apt running when you started the installation? (Perhaps an upgrade being performed on a fresh installation in the background) A lock on apt might explain why things such as git and htpasswd failed to get installed.

Do you have a log file of the installation in `/root/logs/install.log`?

**Comment by tmm22** [comment]
Unfortunately, despite logging in as a root I get this message 
     snap install microk8s --classic

8 packages can be updated.
3 updates are security updates.

Last login: Sat May  4 01:21:46 2019 from 123.211.215.101
root@Ubuntu-1804-bionic-64-minimal ~ #  /root/logs/install.log
-bash: /root/logs/install.log: Permission denied
root@Ubuntu-1804-bionic-64-minimal ~ #  root/logs/install.log
-bash: root/logs/install.log: No such file or directory
root@Ubuntu-1804-bionic-64-minimal ~ #  /root/logs/install.log
-bash: /root/logs/install.log: Permission denied

**Comment by tmm22** [comment]
installation again. Same results any help would be greatly appreciated :-) never had an issue like this before

**Comment by tmm22** [comment]
Basically everything when this script is installing says no such file directory happy to pay for installation

**Comment by liaralabs** [comment]
Did you start the install as a regular (i.e. with sudo), unprivileged user or as root?

What happens if you try to issue the command `apt update && apt upgrade`? Does apt list any errors?

For your previous issues trying to open the log file: the log file isn't meant to be executed... You need to open it with a text editor such as `nano`

It's hard for me to help unless you have a log file or some way to reproduce and unfortunately, I'm not in a position to be providing Linux tutorials -- I've recently done installations on Ubuntu 18.04, so I know the installer is working as intended.

**Comment by tmm22** [comment]
I started as root just like any other fresh install ran the script and that's why got I have attempted to update the system and see if that helps using the stand-app get commands and will attempt to provide you with a log shortly. Please forgive my ignorance when it comes to the UNIX environment. I am disabled and take me l a long time to type hence why I resort to a much copying and pasting of commanders possible

**Comment by tmm22** [comment]
Standard app get commands. I mean, sorry speech recognition error

**Comment by liaralabs** [comment]
I have a feeling that running the upgrade commands before starting the installation should work. 

Otherwise, if you can sftp into the server as root and grab the log from ~/logs and upload that somewhere, it should provide me with the info I need to help you.
