### ISSUE TITLE
Request: Update to Mono-less Jackett

### ISSUE THREAD

**Issue by h4waii** [liaralabs/swizzin#206]
Jackett has [standalone release that works without Mono](https://github.com/Jackett/Jackett#install-on-linux-amdx64). Would increase performance a bit, and as always it's nice to get away from Mono. 

It runs fine, but I'm sure the `box` installer could be updated to use it and whatever calls JackettConsole as well.

**Comment by liaralabs** [comment]
Didn't know they had released this yet. I agree that killing mono wherever possible can only be good :wink:

I'll work on getting it changed over when I've got a bit of time.

**Comment by liaralabs** [comment]
This is live as per 3c398b5bb3d1aacbb37842a8bec41e15571d016f

`box update` should take care of your current installation.
