### ISSUE TITLE
HDD stats for many user and mounted disk 

### ISSUE THREAD

**Issue by F0xt0p** [liaralabs/swizzin#207]
Hello,

I would like to know if we can change HDD stats for each user who each have a different hdd mounted? 

https://imgur.com/a/gQ8i4YA
https://imgur.com/a/8BisONK

I have 4 users and all my user have stat from my os disk ... and my different hdd is mount in  /home/$user$/torrents/rtorrent

anyone can help me for config this please ?

**Comment by liaralabs** [comment]
This has been added in the new panel
