### ISSUE TITLE
tTorrent remove script broken

### ISSUE THREAD

**Issue by bumjrah** [liaralabs/swizzin#21]
root@ns3034822:~# /usr/local/bin/swizzin/remove/rtorrent.sh
This will remove rTorrent and all associated interfaces (ruTorrent/Flood). Press any key to continue.

/tmp
/usr/local/bin/swizzin/remove/rtorrent.sh: line 30: syntax error: unexpected end of file

**Comment by liaralabs** [comment]
Whoopsies! This should be resolved now

**Comment by bumjrah** [comment]
Thanks for the swift update :)
