### ISSUE TITLE
NZBHydra fails to install/launch on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by BrandonG777** [liaralabs/swizzin#211]
![image](https://user-images.githubusercontent.com/1915294/58508230-343d0f00-8159-11e9-9fcd-20d927ad7e01.png)

![image](https://user-images.githubusercontent.com/1915294/58508252-41f29480-8159-11e9-9892-18eeff618c40.png)

Changing the systemd init script to specify python2.7 instead of just python seems to resolve this.

**Comment by liaralabs** [comment]
`python2.7` is the still the default `python` interpreter in Ubuntu 18.04.

This should not be necessary unless you yourself have manually changed the default interpreter with `update-alternatives`
