### ISSUE TITLE
Jackett does not start with current systemd settings

### ISSUE THREAD

**Issue by Niklasmaximilian** [liaralabs/swizzin#213]
I got problems with the autostart script for Jackett. I did not change anything from the configuration itself. I read that Jackett got an update and Mono is not longer required. Maybe, there is something about that...

This is the error I got: 

`sudo systemctl status jackett@plex.service
● jackett@plex.service - jackett
   Loaded: loaded (/etc/systemd/system/jackett@.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2019-05-28 22:43:40 CEST; 1s ago
  Process: 29113 ExecStart=/home/%I/Jackett/jackett --NoRestart (code=exited, status=203/EXEC)
 Main PID: 29113 (code=exited, status=203/EXEC)`

My current solution is to start Jackett in a screen window. No issues so far. However, I really want to go back to the Systemd autostart. Anyone facing similar issues or having a hint how to overcome those?

**Comment by liaralabs** [comment]
I'm using this exact service on my production server, so I'm not sure what the issue would be here.

If you try running the execstart command from your shell as your user (in the jacket folder), do you receive any errors?

**Comment by liaralabs** [comment]
The systemd unit file has been fixed as of 5953ab8310460712fbfce73e52e512f2f9ff2c80

If it's your service file only that's the problem, this commit should fix it (`box update`). However, be aware that there's a lingering update issue within jackett itself that's waiting to be fixed:

https://github.com/Jackett/Jackett/issues/5208
