### ISSUE TITLE
Can't link Flood to rTorrent

### ISSUE THREAD

**Issue by dunnno** [liaralabs/swizzin#214]
Fresh install on Ubuntu 18.04. No probs met excepting the _first_ launch of Flood when it asks for rTorrent Connection Type _TCP or Unix Socket_ // _rTorrent Host_ // _rTorrent Port_.

I chose TCP and 
```
Host: 127.0.0.1
Port: 443
```
(taken from [here](https://github.com/liaralabs/swizzin/wiki/How-to-connect-rTorrent,-Deluge-&-Jackett-with-Sonarr-&-Radarr)) 

Flood throws the error _Cannot connect to rTorrent_ or _Connection could not be verified_. I'm pretty sure the port isn't good but i haven't got any clue of what it could be, can't find any value for SCGI anywhere ([read here](https://github.com/liaralabs/swizzin/issues/135#issuecomment-418173161))

**Comment by liaralabs** [comment]
rTorrent doesn't use an scgi socket as it's a security issue. Instead, rtorrent has been converted to unix sockets:

/var/run/<username>/.rtorrent.sock
