### ISSUE TITLE
Deluge not working

### ISSUE THREAD

**Issue by bumjrah** [liaralabs/swizzin#22]
Access method 1: through domain /deluge get Error 502
Access method 2: through IP:port get message "This site can’t be reached”  and "ERR_CONNECTION_REFUSED" on chrome.

**Comment by liaralabs** [comment]
Is deluge-web running? 502 usually means the application isn't running.

Access method 2's result is to be expected because the bind IP is changed to 127.0.0.1 upon configuring the proxy, so it is no longer accessible remotely

**Comment by bumjrah** [comment]
Yes both deluged & web are both running according to systemctl status deluge*@bumjrah

**Comment by liaralabs** [comment]
Have you tried reloading nginx? Perhaps the deluge config hasn't been loaded yet.

Alternatively, ensure /etc/nginx/apps/deluge.conf and /etc/nginx/conf.d/{username}.deluge exist and that the upstream in conf.d contains the correct port

**Comment by liaralabs** [comment]
I can't reproduce this on a fresh install, so some further questions:

* Have you modified the config at all? Deluge-web or nginx.
* What is your OS?
* Which method did you choose to install Deluge?
* Barring all else, would you be willing to let me poke around your install? you can email me at liara at swizzin dot ltd

**Comment by bumjrah** [comment]
Update the port in the upstream to match the one in the web.conf port & got it working again. Thanks :)
