### ISSUE TITLE
Add Jellyfin Support

### ISSUE THREAD

**Issue by XantherBanter** [liaralabs/swizzin#220]
[Jellyfin Repo](https://github.com/jellyfin/jellyfin)

Please consider Jellyfin as one of the apps that can be installed with swizzin. It's a port from Emby 3.5.2 and is pretty stable on my testing (performs better than Plex in terms of direct Play).

Thanks alot.

**Comment by userdocs** [comment]
There seems to be a conflict here.

https://github.com/jellyfin/jellyfin/issues/691

I set it up and currently it only works at `/emby` though there is some conflicting info in their docs.

We might just have to wait for it to be added to the code.

**Comment by Alpha5K** [comment]
`location ^~ /jellyfin/ {
    proxy_pass http://IP:PORT/;

    proxy_pass_request_headers on;

    proxy_set_header Host $host;

    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Protocol $scheme;
    proxy_set_header X-Forwarded-Host $http_host;

    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $http_connection;
}`

This config works for me and allows me to access it from `/jellyfin`

**Comment by userdocs** [comment]
Thanks. I also found this in the link I posted above https://gist.github.com/oddstr13/6384460ad92bfcef8bf56203e20c345d

I have it working to get through the wizard. Not tested anything after that.

**Comment by userdocs** [comment]
So i made a start on this. It's complicated to say the least. Mostly in regards to ssl.

Here is what i have so far

https://github.com/userdocs/swizzin/blob/master/scripts/install/jellyfin.sh

It's functional but there are oddities in the way URL and addresses are displayed in the gui that i have not solved.

**Comment by NathanBlais** [comment]
Is this still being worked on?
