### ISSUE TITLE
502 nginx, all of a sudden

### ISSUE THREAD

**Issue by dunnno** [liaralabs/swizzin#224]
Looks like nginx died by itself here.

`sudo niginx -t`

gives
```
nginx: [warn] could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```
Having this
`server_names_hash_bucket_size 64;`
this
`server_names_hash_bucket_size 128;`
or by its default
`#server_names_hash_bucket_size 64;`
in `nginx.conf` changes nothing
How could it be ?

**Comment by liaralabs** [comment]
502 is a gateway error, which means "invalid response".

Typically, it's associated with a proxy which points to an endpoint that isn't online or issues with php not running or being misconfigured.

Your output from `nginx -t` doesn't mean anything. There are no errors, only the warning, which doesn't cause any issues.

Is php running?

Check the error logs in `tail -f /var/log/nginx/error.log` & refresh the page while having that in the background. Check if refreshing the page outputs any errors to your log.

**Comment by dunnno** [comment]
Thanks for clarification, googling isn't the best sometimes :)

Here is what shows in the error log when refreshing the page : 
```
2019/07/26 21:04:25 [error] 18419#18419: *3072 FastCGI sent in stderr: "PHP message: PHP Notice:  A non well formed numeric value encountered in /srv/panel/widgets/data.php on line 11
PHP message: PHP Notice:  A non well formed numeric value encountered in /srv/panel/widgets/data.php on line 11
PHP message: PHP Notice:  A non well formed numeric value encountered in /srv/panel/widgets/data.php on line 12
PHP message: PHP Notice:  A non well formed numeric value encountered in /srv/panel/widgets/data.php on line 12" while reading response header from upstream, client: 193.56.245.110, server: mydomain.com, request: "GET /widgets/data.php?_=1564175000972 HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "mydomain.com", referrer: "https://mydomain.com/"
```

**Comment by Wyall** [comment]
For me php wasn't running for some reason, could you check systemctl status php7.2-fpm ? Happened out of nowhere and restart didn't help. But maybe it's not the same problem, who knows?

**Comment by dunnno** [comment]
Here you are 
```
● php7.2-fpm.service - The PHP 7.2 FastCGI Process Manager
   Loaded: loaded (/lib/systemd/system/php7.2-fpm.service; disabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-07-26 20:25:41 UTC; 1 day 18h ago
     Docs: man:php-fpm7.2(8)
 Main PID: 6518 (php-fpm7.2)
   Status: "Processes active: 0, idle: 3, Requests: 6867, slow: 0, Traffic: 0req/sec"
    Tasks: 4 (limit: 4640)
   CGroup: /system.slice/php7.2-fpm.service
           ├─ 6518 php-fpm: master process (/etc/php/7.2/fpm/php-fpm.conf)
           ├─21324 php-fpm: pool www
           ├─21577 php-fpm: pool www
           └─21593 php-fpm: pool www

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
```

**Comment by liaralabs** [comment]
Your php service is disabled (as I eluded to earlier). It's not being started on a fresh boot, which I'm guessing is the source of your issues.

```
(/lib/systemd/system/php7.2-fpm.service; disabled; vendor preset: enabled)
```
There was a brief bug on installations that was disabling the php7.2-fpm service, accidentally. You just need to re-enable the service and it should start automatically.

Otherwise, if the php service is running and you're still receiving a gateway error, that's more tricky. I'd start by asking if you have any other versions of PHP running on the server, as that might cause similar issues (if nginx was configured to use the wrong php).

**Comment by dunnno** [comment]
Ok that’s what I read as well, even my non-tech savvy head understood it ;).
Can you give me the command to restart the service please as I’m not sure how to write it.

No any other stuff on the server, that comes to mind, despite your script.

Thanks again, you rock!

**Comment by liaralabs** [comment]
`sudo systemctl enable --now php7.2-fpm` will enable and start the service when you hit `enter`

**Comment by dunnno** [comment]
Thanks, enabling the service gives me back the Swizzin dashboard. Unfortunately, Jackett still returns a 502 (any disabling, reinstalling, re-enabling etc, no luck)

**Comment by liaralabs** [comment]
Jackett is a separate issue and the errors have been documented here and on the Jackett issue tracker (issue 5208 on jackett)

https://github.com/liaralabs/swizzin/issues/213
