### ISSUE TITLE
Wrong type log spamming

### ISSUE THREAD

**Issue by RaymondSchnyder** [liaralabs/swizzin#225]
**Describe the bug**
The log is getting spammed by /srv/panel/widgets/data.php
The message getting spammed is this one:

``2019/08/02 22:43:58 [error] 456#456: *138 FastCGI sent in stderr: "PHP message: PHP Notice:  A non well formed numeric value encountered in /srv/panel/widgets/data.php on line 11PHP message: PHP Notice:  A non well formed numeric value encountered in /srv/panel/widgets/data.php on line 11PHP message: PHP Notice:  A non well formed numeric value encountered in /srv/panel/widgets/data.php on line 12PHP message: PHP Notice:  A non well formed numeric value encountered in /srv/panel/widgets/data.php on line 12" while reading response header from upstream, client: 192.168.122.20, server: _, request: "GET /widgets/data.php?_=1564778633723 HTTP/1.0", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:",``

**To Reproduce**
1. setup 
2. nothing more i guess

**Expected behavior**
the log is not getting spammed by this message.

**Server Info (please complete the following information):**
 - OS: Debian 10
- Type: KVM guest
- Network interface name: ens18
- Network type: bridged

**Additional context**
Temporary workaround:
in ``/srv/panel/widgets/data.php`` on line 11 change
``$tbps = $tx[1] - $tx[0];``
to
``$tbps = intval($tx[1]) - intval($tx[0]);``

and on line 12 change
``$rbps = $rx[1] - $rx[0];``
to
``$rbps = intval($rx[1]) - intval($rx[0]);``

**Comment by liaralabs** [comment]
Thanks for the report. I'm not overly a PHP developer and the dashboard was inherited directly from QB with code that works but has issues such as this. I took some time a couple weeks to try to nail down all the notices and errors, but this one eluded me.

I've included your fix and with that, the error log should actually only be reporting serious errors, even while the dashboard is open.
