### ISSUE TITLE
I just Nikto my seedbox. Any way of fixing these?

### ISSUE THREAD

**Issue by SotirisParaskevopoulos** [liaralabs/swizzin#226]
Hi i was foolng around with my seedbox and Nikto reported some issues. I'm no expert in any way but could they be fixed? How harmful are they (curiosity)?

```
- The anti-clickjacking X-Frame-Options header is not present.
- The X-XSS-Protection header is not defined. This header can hint to the user agent to protect against some forms of XSS
- The site uses SSL and the Strict-Transport-Security HTTP header is not defined.
- The site uses SSL and Expect-CT header is not present.
- The X-Content-Type-Options header is not set. This could allow the user agent to render the content of the site in a different fashion to the MIME type
```

**Comment by liaralabs** [comment]
SSL parameters are stored in the file `/etc/nginx/snippets/ssl-params.conf`

There's awash of info on these issues available on a quick Google search:

X-Frame-Options:

https://www.netsparker.com/web-vulnerability-scanner/vulnerabilities/missing-x-frame-options-header/

(x-frame-options is indeed being set to `SAMEORIGIN`)

X-XSS-Protection header:

https://www.netsparker.com/web-vulnerability-scanner/vulnerabilities/missing-x-xss-protection-header/

Strict-Transport-Security:

https://www.netsparker.com/web-vulnerability-scanner/vulnerabilities/http-strict-transport-security-hsts-policy-not-enabled/

Expect-CT

https://www.netsparker.com/web-vulnerability-scanner/vulnerabilities/expect-ct-not-enabled/

X-Content-Type-Options

https://www.netsparker.com/web-vulnerability-scanner/vulnerabilities/missing-content-type-header/

X-Frame-Options and X-Content-Type-Options *are* defined though. I'm assuming the basic http auth is likely interfering with the headers being grabbed correctly.

That leaves 3: Of the 3, 2 are considered "Best Practice" with a negligible impact on any sort of security.

This leaves HSTS which the user can enable if they so desire if they understand the implications of the header. The option is in `ssl-params.conf` but not enabled. You can enable it if you like; however if your SSL fails for any reason you will *NOT* be able to access your box via web (this includes using a self-signed certificate, which is generally the default on any swizzin installation). I'd probably recommend removing the `includeSubdomains` bit if you're on a top-level of your domain as the header will be cached for the duration and applied to all subdomains (even if the header isn't set explicitly on the subdomain configuration itself)
