### ISSUE TITLE
Flood error in a fresh install

### ISSUE THREAD

**Issue by Albvadi** [liaralabs/swizzin#227]
**Describe the bug**
Selecting flood in the install packages not install flood

**To Reproduce**
1. Fresh install
2. Select flood for the package installs

**Expected behavior**
Run flood correctly

**Server Info (please complete the following information):**
 - OS:  Debian GNU/Linux 9.9 (stretch)

**Additional context**
Looking in the `install-log` there are the following errors:
```
Configurando nodejs (4.8.2~dfsg-1) ...
update-alternatives: utilizando /usr/bin/nodejs para proveer /usr/bin/js (js) en modo automático
/usr/local/bin/swizzin/install/flood.sh: línea 24: npm: no se encontró la orden
Cloning into '.flood'...
-su: npm: no se encontró la orden
-su: npm: no se encontró la orden

```
npm isn´t installed in the system...

**Comment by liaralabs** [comment]
node should be fixed as of 353b97f633eab54e1c1ba41681a6e6d81fc2e01a

Please re-open if you're still facing issues installing the lounge or flood.
