### ISSUE TITLE
Conflicting distribution error - plex repository

### ISSUE THREAD

**Issue by Ekynox** [liaralabs/swizzin#23]
Hi liara,
**Issue:**
after installing plex, an `apt-get update` produce the following error message:
> W: Conflicting distribution: https://downloads.plex.tv/repo/deb public InRelease (expected public but got )

**Proposed solution:**
replace the following line in `/master/scripts/install/plex.sh`
`echo "deb https://downloads.plex.tv/repo/deb/ public main" > /etc/apt/sources.list.d/plexmediaserver.list`
with
`echo deb https://downloads.plex.tv/repo/deb ./public main > /etc/apt/sources.list.d/plexmediaserver.list`

**Temporary Workaround**
Modify the script locally before installing plex:
`sed -i -e "s~plex.tv/repo/deb/ public~plex.tv/repo/deb ./public~" /etc/swizzin/scripts/install/plex.sh`

**Reference:**
https://support.plex.tv/hc/en-us/articles/235974187-Enable-repository-updating-for-supported-Linux-server-distributions

**Comment by liaralabs** [comment]
Thank you for the detailed bug report, complete with a solution! I've made the change you proposed and verified its functionality :)
