### ISSUE TITLE
issue to install rutorrent

### ISSUE THREAD

**Issue by root-host** [liaralabs/swizzin#232]
Hello
im trying to install rutorrent and nginx but after i run the scrpit as root im getting error that nginx phpmode command not found 

can you fix the script?

debian 10 64 bit cleant install whit all latest updates.

**Comment by liaralabs** [comment]
I cannot replicate your issue in a clean environment (Vultr VPS using Buster 10 template). So if you're still having issues, I'll need more info:

- Logs (Logs from your first install are in `/root/logs/install.log`)
- Any output from the terminal that may have looked like an error
- Steps taken to replicate your error

Please be aware that if you've **just** spun up your dedicated server or VPS that apt could be running in the background and updating your OS to the latest updates. If apt is running, it will create a lock file that will cause all apt commands to fail entirely (thus pulling no dependencies) until the original process has completed.

```
root@vultr:~# ps aux | grep apt
root      1566  0.0  0.0   2388   756 ?        Ss   17:55   0:00 /bin/sh /usr/lib/apt/apt.systemd.daily install
root      1570  0.0  0.1   2388  1656 ?        S    17:55   0:00 /bin/sh /usr/lib/apt/apt.systemd.daily lock_is_held install
root      1631 53.5  1.2  19940 12472 pts/0    Ss+  17:55   0:04 /usr/bin/dpkg --status-fd 12 --no-triggers --unpack --auto-deconfigure /var/cache/apt/archives/linux-image-4.19.0-5-amd64_4.19.37-5+deb10u2_amd64.deb
root      1639  0.0  0.0  12252   904 pts/0    S+   17:55   0:00 dpkg-deb --fsys-tarfile /var/cache/apt/archives/linux-image-4.19.0-5-amd64_4.19.37-5+deb10u2_amd64.deb
root      1640  0.3  0.0  12252   156 pts/0    S+   17:55   0:00 dpkg-deb --fsys-tarfile /var/cache/apt/archives/linux-image-4.19.0-5-amd64_4.19.37-5+deb10u2_amd64.deb
root      1641 42.1  0.9  20448  9756 pts/0    R+   17:55   0:03 dpkg-deb --fsys-tarfile /var/cache/apt/archives/linux-image-4.19.0-5-amd64_4.19.37-5+deb10u2_amd64.deb
root      1658  0.0  0.0   6076   824 pts/1    S+   17:55   0:00 grep apt
root@vultr:~#
```

**Comment by Xolsurf3r** [comment]
> 
> 
> Hello
> im trying to install rutorrent and nginx but after i run the scrpit as root im getting error that nginx phpmode command not found
> 
> can you fix the script?
> 
> debian 10 64 bit cleant install whit all latest updates.

I came across similar issues while on Debian 10 Buster (updated)on KVM. The install seem to get broken after the install.
However can confirm this can be fixed from the OS part. 
Swizzin is not at fault. Debian 9 or Ubuntu work flawless.
