### ISSUE TITLE
vsftpd blank server

### ISSUE THREAD

**Issue by R34V3N** [liaralabs/swizzin#235]
Hi,
I have a problem with vsftpd. I can connect to my ftp server with firefox and filezilla but we can't see files in my home.

cat /etc/vsftpd.conf 
listen=NO
listen_ipv6=YES
anonymous_enable=NO
local_enable=YES
write_enable=YES
force_dot_files=YES
local_umask=022
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES
utf8_filesystem=YES
rsa_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
rsa_private_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
ssl_enable=YES
pam_service_name=vsftpd
secure_chroot_dir=/var/run/vsftpd/empty

#lock ftp users to their home directory
chroot_local_user=YES
allow_writeable_chroot=YES

#ascii_upload_enable=YES
#ascii_download_enable=YES
#ftpd_banner=Welcome to blah FTP service.

#############################################
#Uncomment these lines to enable FXP support#
#############################################
pasv_promiscuous=YES
port_promiscuous=YES

###################
#Set a custom port#
###################
#listen_port=

**Comment by liaralabs** [comment]
It may be related to the chroot options you added -- have you tried disabling the additions you made to the conf file to troubleshoot?
