### ISSUE TITLE
proxypass giving me 401 on tautulli

### ISSUE THREAD

**Issue by Suiziide** [liaralabs/swizzin#242]
I dont understand this one either, sorry if it's bothersome.

But when I use the following in my etc/nginx/sites-enabled/default

server {
 listen 80;
 listen [::]:80;
 server_name plex.[REDACTED].cc;

 location / {
 proxy_pass https://localhost:32400;
 auth_basic "Restricted Remote";
 auth_basic_user_file /etc/htpasswd;
  }
}

it prompts me for a password when trying to access tautulli, annd when i enter the password, it just says 401 restricted.. When i comment out the proxypass it works fine.. I don't understand because it's 2 different server names and ports (i thinnk tautulli is 8181?)

All the other apps are working fine, it's only tautulli

**Comment by Suiziide** [comment]
I solved it myself.. By removing that block and only listening on port 443, it solved the problem

**Comment by liaralabs** [comment]
GitHub issues are not here for support and customizing the scripts and configs. These are for reporting bugs and issues with the project. Please do not open tickets unless you are experiencing a bug with the project (not including self-inflicted bugs).

You can try asking in Discord, but that would be up to community support. I generally don't respond to requests from users who are looking to change the intended behavior of defaults as this is outside my scope of project support (and if I do, it will be as time permits).

The files in question are "owned" by swizzin and thus subject to change and modification by update/upgrade scripts. Thus, any modifications made to swizzin owned files may be subject to complete rewriting.

**Comment by Suiziide** [comment]
I'm sorry, I will ask on discord in the future..

Thank you for your hard work!
