### ISSUE TITLE
Error on installing autodl

### ISSUE THREAD

**Issue by Lucif3r-MorningSter** [liaralabs/swizzin#246]
On one of my server autodl was throwing error so i decided to remove autodl and install again. After removing autodl when i try to install i get this error:

Installing autodl
APT-GET could not find all the required sources. Script Ending.

**To Reproduce**
1. box remove autodl
2. box install autodl

OS: ubuntu 16.04 LTS

**Comment by liaralabs** [comment]
I cannot reproduce your issue with my installation; however, I've just updated the autodl scripts to be a bit more verbose when throwing an error (it should state which dependency it cannot install now).

That said, if you already installed autodl, the dependencies grabbed by apt should already be installed on your server.

Can you please try re-installing autodl with the updates and let me know which dependency it fails on?

**Comment by liaralabs** [comment]
`apt-get` commands were causing an exit code and thus a script exit due to an apt front-end lock -- unrelated to swizzin.
