### ISSUE TITLE
Subsonic doesn't install on Debian 10 (No openjdk-8-jre)

### ISSUE THREAD

**Issue by SavageCore** [liaralabs/swizzin#247]
**Describe the bug**
Subsonic will not run after installation due to missing openjdk-8-jre package.
Really there are 2 issues as the box install script should exit when dependencies cannot be installed.

**To Reproduce**
1. fresh swizzin install on Debian 10 (Buster)
1. box install subsonic

**Expected behavior**
Subsonic to install and run

**Server Info (please complete the following information):**
```# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Additional context**

`tail -f /srv/subsonic/subsonic_sh.log`: 
> /usr/share/subsonic/subsonic.sh: 34: /usr/share/subsonic/subsonic.sh: java: not found

```
Installing subsonic
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package openjdk-8-jre
```

openjdk-8-jre only available from `sid` as seen [here](https://packages.debian.org/search?searchon=names&keywords=openjdk-8-jre)

**Comment by SavageCore** [comment]
Related to https://github.com/liaralabs/swizzin/issues/219?

**Comment by codeddarkness** [comment]
## DEBIAN 10 BUSTER SUBSONIC INSTALL
## DO INSTALL
wget https://s3-eu-west-1.amazonaws.com/subsonic-public/download/subsonic-6.1.6.deb
dpkg -i subsonic-6.1.6.deb 
  
useradd -r subsonic
nano /etc/default/subsonic 

tail -F /var/subsonic/subsonic_sh.log 
java -version
## !! wrong java version jetty 503 page error


## INSTALL CORRECT OPENJDK-8 FROM STRECH MIRROR
apt-get install software-properties-common
apt-add-repository 'deb http://security.debian.org/debian-security stretch/updates main'
  
apt-get update
## INSTALL CORRECT JDK
apt-get install openjdk-8-jdk

## DISPLAY ALT JDK AND SELECT JDK 8
update-alternatives --display java

update-alternatives --config java

java -version
'openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-1~deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)'
  
## RESTART SUBSONIC SERVICE
service subsonic restart

## OPEN BROWSER TO subsonicIP:port
