### ISSUE TITLE
box upgrade rutorrent does not upgrade the UI version from 3.8 to 3.9

### ISSUE THREAD

**Issue by decompiled** [liaralabs/swizzin#248]
Command:
sudo box upgrade rutorrent

Output:
Updating swizzin local repository
M       scripts/install/bazarr.sh
M       scripts/install/filebrowser.sh
M       scripts/install/lidarr.sh
M       scripts/install/sickchill.sh
M       scripts/install/wireguard.sh
M       scripts/nginx/bazarr.sh
M       scripts/nginx/filebrowser.sh
M       scripts/nginx/lidarr.sh
M       scripts/nginx/sickchill.sh
M       scripts/remove/bazarr.sh
M       scripts/remove/filebrowser.sh
M       scripts/remove/lidarr.sh
M       scripts/remove/sickchill.sh
M       scripts/remove/tautulli.sh
M       scripts/remove/wireguard.sh
M       scripts/update/libtorrent.sh
M       scripts/update/node.sh
M       scripts/update/plex.sh
M       scripts/update/sickchill.sh
Already on 'master'
Your branch is up-to-date with 'origin/master'.
From https://github.com/liaralabs/swizzin
 * branch            master     -> FETCH_HEAD
HEAD is now at b209bb0 Cleanup autodl installation and removal (#246)
HEAD is now at 65f8719 updated css aesthetics to address overlapping
Already up-to-date.
Upgrading rutorrent

This results to 3.8 rutorrent.
New installs of swizzin results to 3.9 rutorrent.  Is this bug or intention?  Thank you!

**Comment by liaralabs** [comment]
https://github.com/liaralabs/swizzin/blob/master/scripts/upgrade/rutorrent.sh#L4

Intention. Upgrading ruTorrent is not an easy affair as sometimes files swizzin has modified get upgraded in git and cause merge conflicts.

There is an unsupported upgrade script in the dev branch:

https://github.com/liaralabs/swizzin/blob/devel/scripts/upgrade/rutorrent.sh

Use at your own risk, it may break your ruTorrent install and you'll have to reinstall ruTorrent to fix.
