### ISSUE TITLE
Broken script (around the sendmail part)

### ISSUE THREAD

**Issue by austinthetaco** [liaralabs/swizzin#249]
**Describe the bug**
brand spankin new install of ubuntu lts, i run the script, it gets to the sendmail bit,  says "finalizing sendmail installation" then nukes my ssh connection. To the point where i can no longer ssh even after a restart. SSH breaking aside, it also doesn't finish the script/finish installing. I have to rollback my vm to before the script to get ssh back. 

**Server Info (please complete the following information):**
 - OS: Ubuntu 18.04 LTS Server

**Comment by epiclulz666** [comment]
can confirm experiencing the same error with setup script on Ubuntu 18.04 LTS Server

**Comment by liaralabs** [comment]
CSF has been removed entirely, thus is issue is no longer relevant
