### ISSUE TITLE
Tautulli nginx config missing basic authentication

### ISSUE THREAD

**Issue by quietvoid** [liaralabs/swizzin#250]
The Tautulli endpoint is not protected by htpasswd, the install script does not add the auth_basic lines to `/etc/nginx/apps/tautulli.conf`

I would've made a PR but I don't know if Tautulli can be setup for multiple users.

Maybe intentional because the application has authentication built-in?

**Comment by liaralabs** [comment]
As per the pull request (https://github.com/liaralabs/swizzin/commit/37bdba4fa6cefd2ee6f33d857fb797b8dffa3b3b), this was intentionally removed to allow for compatibility with the mobile app. If you would like to add authentication, you can enable it from the app.
