### ISSUE TITLE
User can see other users files and folders on ssh

### ISSUE THREAD

**Issue by Lucif3r-MorningSter** [liaralabs/swizzin#251]
Today one of my user told me he can see all my username's and their files via ssh terminal. I also checked and yes they can! on ftp they are jailed on their own directory but on ssh they can go to any folder they want.

**Comment by liaralabs** [comment]
By default, users folders are not given "Other" read permissions. User home directories are given the permission structure `750` by default.

Initial user during setup: https://github.com/liaralabs/swizzin/blob/master/setup.sh#L161
Adduser with box: https://github.com/liaralabs/swizzin/blob/master/scripts/box#L243

A quick search through the project for every instance of `chmod` determines that there are no misplaced `chmod`s in the project that might accidentally revert permissions on a user's home directory to `755`. Thus, if your user directories are `755` and have `other: read` permissions, it is not a result of swizzin.

Further, please make sure that the users may not have accidentally been added to the other users's group, as this would allow them `group: read` permissions which are allowed (as www-data needs certain group read privileges for panel data).

If you are referring to other folders on the drive, then yes. If you require other folders than the following directories to have more restrictive permissions, then you would be required to lock down permissions on directories that are not:

```
/home/<username>
/home/<username>/.ssl
/home/<username>/.wireguard
/etc/wireguard
/etc/swizzin/scripts
/etc/nginx/ssl
```

I am open to suggestions of *system related* files that should be further locked down, but any custom mount related permissions should be left to the user to decide.
