### ISSUE TITLE
Nginx directory showing size as shortened without decimal

### ISSUE THREAD

**Issue by sagivstern** [liaralabs/swizzin#256]
Hello,
This seems to be kinda stupid and not very important but nginx directory never shows the size shortened with decimal
example:
actual file size 3.3 GB
shown file size 3G
I've tracked the bug to ngx-fancyindex git [https://github.com/aperezdc/ngx-fancyindex/pull/53](url)
but noticed swizzin uses Naereen git version [https://github.com/Naereen/Nginx-Fancyindex-Theme](url)

Wasn't sure if to post here or there, worse case delete this post and I apologize.

Thanks for your great work!

**Comment by liaralabs** [comment]
The fancy index theme relies on the ngx-fancyindex module, thus they are both technically being used here.

You can enable the directive you linked to in your issue by editing the file `/etc/nginx/snippets/fancyindex.conf` and changing the directive:

```
fancyindex_exact_size off;
```
to
```
fancyindex_exact_size on;
```
And then reloading nginx.

However, it will display the byte value of the file, not any extra decimal points. It doesn't look like there is a directive that allows you to define the decimal places yourself.

**Comment by sagivstern** [comment]
Thanks for the reply,
Then it should make sense to have the decimal value since ngx-fancyindex fixed it, wont it?
but it still seems broken.
Prior to this post I did find and change fancyindex_exact_size to on, doesnt quite do what I wanted.

Anyways thank you again.
Closed due to just accepting this.
