### ISSUE TITLE
How Do I Use Swizzin for SFTP Client on Seedbox?

### ISSUE THREAD

**Issue by koolx** [liaralabs/swizzin#257]
Hi. Not really an issue. But I'd like to know how to use an sftp client on a dedi. I read that swizzin was the easiest way for that. I'm a newbie fyi... Thanks.

**Comment by sysvinits** [comment]
For SFTP you use a client that supports the SFTP protocol. Some examples are FileZilla and terminus. As long as you have ssh installed (you should 100% already) it will work. Just put your IP/domain as the host and username and password as the login (this will be the same as ssh) for SFTP. This will be on port 22. If you're not transferring to home then I would use something like Rclone from server to server. 

[](https://help.one.com/hc/en-us/articles/115005585709-How-do-I-connect-to-an-SFTP-server-with-FileZilla)

**Comment by liaralabs** [comment]
As per the readme:

> Please use Discord for all community functions, feathub for feature requests and leave issues for actual issues.

Issues are not a place to receive support. Please consider dropping by the discord if you're looking for help such as this.
