### ISSUE TITLE
xmr-stack no longer supports monero

### ISSUE THREAD

**Issue by rbax82** [liaralabs/swizzin#260]
**Describe the bug**
/usr/local/bin/xmr-stak -c /home/soc/.xmr/config.txt -C /home/soc/.xmr/pools.txt --cpu /home/soc/.xmr/cpu.txt

**To Reproduce**
/usr/local/bin/xmr-stak -c /home/soc/.xmr/config.txt -C /home/soc/.xmr/pools.txt --cpu /home/soc/.xmr/cpu.txt

[2020-01-14 15:33:21] : Unrecognised coin 'monero', your options are:
        - bbscoin
        - bittube
        - cryptonight
        - cryptonight_bittube2
        - cryptonight_masari
        - cryptonight_haven
        - cryptonight_heavy
        - cryptonight_lite
        - cryptonight_lite_v7
        - cryptonight_lite_v7_xor
        - cryptonight_r
        - cryptonight_superfast
        - cryptonight_turtle
        - cryptonight_v7
        - cryptonight_v8
        - cryptonight_v8_double
        - cryptonight_v8_half
        - cryptonight_v8_reversewaltz
        - cryptonight_v8_zelerius
        - cryptonight_v7_stellite
        - cryptonight_gpu
        - cryptonight_conceal
        - graft
        - haven
        - lethean
        - masari
        - qrl
        - ryo
        - torque
        - plenteum
        - zelerius

**Expected behavior**
Starts mining
**Server Info (please complete the following information):**
 - OS: Debian 10

**Additional context**
Add any other context about the problem here. Logs, terminal output, etc.

**Comment by khnielsen** [comment]
It would be beneficial to know what version of xmr-stak you have installed.

**Comment by rbax82** [comment]
Version: xmr-stak 2.10.8 67cf951

**Comment by liaralabs** [comment]
I'm aware of this issue but I haven't had time to implement a fix yet. It's on my list of things to-do.

The issue is that on Nov 30 monero hardforked to a new algorithm (randomx) and xmr-stak has zero support for the new algorithm. I intend to fix the package by removing xmr-stak and instead utilizing the package xmrig. The base work is done but I haven't had any time to polish up the script and write something that will upgrade current users to the new package.

**Comment by liaralabs** [comment]
xmr-stak has now been replaced with xmrig. You should be able to trigger the forced upgrade by running `box update`. The installer will attempt to read your current configuration and port them over to xmrig for minimal effort; however, it will also give you a chance to change them as well.
