### ISSUE TITLE
ERROR: Web server not detected. Please install nginx and restart panel install.

### ISSUE THREAD

**Issue by JOduMonT** [liaralabs/swizzin#261]
**Describe the bug**
I know I'm silly but you claim we decide to install or not stuff so
I choose to install panel and not nginx
but apparently nginx is a prerequisite for panel

**To Reproduce**
1. fire a box at scaleway with Debian 10
2. ssh the box
3. bash <(wget -O- -q https://raw.githubusercontent.com/liaralabs/swizzin/master/setup.sh)
4. choose only panel (not nginx)
5. next

**Expected behavior**
the dependency should be manage by the script and/or be more explicit 

**Server Info (please complete the following information):**
 - OS: Debian 10

**Additional context**
![image](https://user-images.githubusercontent.com/5204724/73415397-5ae4c280-4344-11ea-85a8-318c075ce26f.png)

**Comment by liaralabs** [comment]
Panel install now prompts user to install nginx if it's not installed.
