### ISSUE TITLE
nginx problem

### ISSUE THREAD

**Issue by LaMpiR** [liaralabs/swizzin#267]
So, due to this time, staying and home and I have been doing some server updates and so on.

Performed **box upgrade nginx** and after **sudo box upgrade rtorrent** and I choose 0.9.8.

Rebooted the server, nginx wont start. Installed 0.9.6. rtorrent. Still no. This is the error I get:

```
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-03-24 20:52:43 UTC; 48s ago
     Docs: man:nginx(8)
  Process: 3818 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)

Mar 24 20:52:43 testtest systemd[1]: Starting A high performance web server and a reverse proxy server...
Mar 24 20:52:43 testtest nginx[3818]: nginx: [emerg] BIO_new_file("/etc/nginx/ssl/website/fullchain.pem")
Mar 24 20:52:43 testtest nginx[3818]: nginx: configuration file /etc/nginx/nginx.conf test failed
Mar 24 20:52:43 testtest systemd[1]: nginx.service: Control process exited, code=exited status=1
Mar 24 20:52:43 testtest systemd[1]: nginx.service: Failed with result 'exit-code'.
Mar 24 20:52:43 testtest systemd[1]: Failed to start A high performance web server and a reverse proxy server.
Mar 24 20:52:50 testtest systemd[1]: nginx.service: Unit cannot be reloaded because it is inactive.
Mar 24 20:52:50 testtest systemd[1]: nginx.service: Unit cannot be reloaded because it is inactive.
Mar 24 20:52:50 testtest systemd[1]: nginx.service: Unit cannot be reloaded because it is inactive.
~
```
Please help.

**Comment by liaralabs** [comment]
The error you're receiving has nothing to do with rTorrent but rather your ssl certificate:
```
Mar 24 20:52:43 testtest nginx[3818]: nginx: [emerg] BIO_new_file("/etc/nginx/ssl/website/fullchain.pem")
```
I do not know if you have scrubbed info from your logs, but the location of your ssl certs should be at:

```
/etc/nginx/ssl/domain.com
```

If your conf file indeed says `/etc/nginx/ssl/website/fullchain.pem` then it's possible some modification was made to the hostname field which swizzin greps before starting the repair process. You need to manually redefine the hostname in your nginx conf (`/etc/nginx/sites-enabled/default`) and ensure that the ssl locations also match this hostname as well -- otherwise nginx will fail to start because the SSL certificates which are required for function are not found.

You may try running the let's encrypt script again, but I can't guarantee it won't create more problems

**Comment by LaMpiR** [comment]
I have removed it, installed, restarted and it started. But my panel was removed. Installed the panel.

But I get only this when I log in:
502 Bad Gateway
nginx


php.7.2-fpm is somehow not working.

```

root@testtest:/etc# systemctl status php7.2-fpm.service
● php7.2-fpm.service - The PHP 7.2 FastCGI Process Manager
   Loaded: loaded (/lib/systemd/system/php7.2-fpm.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-03-24 21:28:00 UTC; 1min 28s ago
     Docs: man:php-fpm7.2(8)
  Process: 18544 ExecStart=/usr/sbin/php-fpm7.2 --nodaemonize --fpm-config /etc/php/7.2/fpm/php-fpm.conf (code=exited, status=78)
 Main PID: 18544 (code=exited, status=78)

Mar 24 21:28:00 testtest systemd[1]: Starting The PHP 7.2 FastCGI Process Manager...
Mar 24 21:28:00 testtest php-fpm7.2[18544]: [24-Mar-2020 21:28:00] ERROR: failed to open configuration file '/etc/php/7.2/fpm/php-fpm.
Mar 24 21:28:00 testtest php-fpm7.2[18544]: [24-Mar-2020 21:28:00] ERROR: failed to load configuration file '/etc/php/7.2/fpm/php-fpm.
Mar 24 21:28:00 testtest php-fpm7.2[18544]: [24-Mar-2020 21:28:00] ERROR: FPM initialization failed
Mar 24 21:28:00 testtest systemd[1]: php7.2-fpm.service: Main process exited, code=exited, status=78/n/a
Mar 24 21:28:00 testtest systemd[1]: php7.2-fpm.service: Failed with result 'exit-code'.
Mar 24 21:28:00 testtest systemd[1]: Failed to start The PHP 7.2 FastCGI Process Manager.
```

Certificate is working now.

**Comment by liaralabs** [comment]
The php configuration files are missing -- if you removed nginx, it's possible the related php configs were also removed (tbh, nginx was never a package that was really intended to be uninstalled and the removal package has been left neglected as a result -- looking through it now, it's not exactly up to date).

You might have some luck if you try reinstalling php-fpm from apt:
```
apt install --reinstall php-fpm
```

This should hopefully re-create any config files that would be necessary for php-fpm to run.

**Comment by Lukylix** [comment]
`apt --purge remove nginx* php*
apt autoremove
apt update
apt upgrade
apt install php php-fpm`

**Comment by LaMpiR** [comment]
> The php configuration files are missing -- if you removed nginx, it's possible the related php configs were also removed (tbh, nginx was never a package that was really intended to be uninstalled and the removal package has been left neglected as a result -- looking through it now, it's not exactly up to date).
> 
> You might have some luck if you try reinstalling php-fpm from apt:
> 
> ```
> apt install --reinstall php-fpm
> ```
> 
> This should hopefully re-create any config files that would be necessary for php-fpm to run.

I have tried that already and with no luck.

**Comment by LaMpiR** [comment]
Box update rutorrent solved the rutorrent problem. Sonarr is working as well. 

Rutorrent looks totally weird and small, but will thinker with theme options :)
