### ISSUE TITLE
adduser script fails

### ISSUE THREAD

**Issue by tfp1** [liaralabs/swizzin#27]
shell response is:
> /usr/local/bin/swizzin/install/rtorrent.sh: line 236: _ruconf: command not found

Resolution: edit /usr/local/bin/swizzin/install/rtorrent.sh
line 236, _ruconf --> _rconf

**Comment by liaralabs** [comment]
The script should still complete regardless that it can't find that function. I forgot to remove the call to _ruconf in rtorrent.sh for the adduser function; however, rutorrent.sh is still being called, which is the script responsible for configuring new users with ruTorrent.
