### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by amil25** [liaralabs/swizzin#270]
Hi,

I'm not able to access the swizzin panel getting 502 Bad Gateway since yesterday. but I can access all the apps like sonarr radarr with my domain. 
![11](https://user-images.githubusercontent.com/62983105/78107694-0377d700-7407-11ea-9946-68b30f7a81a0.JPG)

**Comment by liaralabs** [comment]
If you're still having issues, have you tried running `box update` and `box upgrade panel` lately? Many of the smaller issues have been patched by now. Otherwise, if you're still having issues please, post output from

`systemctl status panel` and `journalctl -u panel`

**Comment by liaralabs** [comment]
Closing due to no updates
