### ISSUE TITLE
favicon for panel not displaying

### ISSUE THREAD

**Issue by aholmes97** [liaralabs/swizzin#272]
favicon on the panel index is not showing

**To Reproduce**
Install panel
Visit panel

**Expected behavior**
Favicon should display

**Server Info (please complete the following information):**
 - OS: Debian 10

**Additional context**
Within /opt/swizzin/swizzin/templates/index.html updating
`<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">`
  to
`<link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon/favicon.ico') }}">`
resolves the issue

**Comment by liaralabs** [comment]
This got glossed over at some point when I moved it from the base directory of static to its own folder :) I've applied the fix and pushed it.

In the future, please direct all bugs/issues with the panel to the proper repo (liaraliabs/swizzin_dashboard)

**Comment by aholmes97** [comment]
Will do!
