### ISSUE TITLE
Problem with rutorrent/autodl

### ISSUE THREAD

**Issue by LaMpiR** [liaralabs/swizzin#273]
Hi. I have updated to the new panel, looks very good :)

I have decided to install autodl-irrsi as well. I have configured everything and it is working as it should, but it crashes sometimes.

Left it over night, worked until few hours ago. Opened rutorrent, autodl problem, restarted autodl from the panel. Nick appears on the IRC but now I cannot open rutorrent anymore. I have restarted rtorrent as well as nginx, but no luck.

After loading for quite some time, I get the error:

[03.04.2020 11:25:55] WebUI started.
[03.04.2020 11:26:55] Bad response from server: (504 [error,getplugins]) Gateway Time-out

I restart the server and everything works for few hours.

**Comment by flying-sausages** [comment]
Did you check any logs? You might find some relevant info under one of the file in `/var/log`
