### ISSUE TITLE
Panel no longer has graphs

### ISSUE THREAD

**Issue by Fuzzydroid** [liaralabs/swizzin#274]
The panel no longer has any graphs. All the stats are still there and it's working, but the graphs are gone.

I installed Deluge 1.3 and it was working but I was getting a 502 error for the web portal, ruTorrent was working fine though. I decided to start with updating nginx, using "box upgrade nginx". Following that, the 502 error was gone but the panel had changed.

Since then, I've tried "box update" and restarting the panel service, but neither has worked. I've attached a screenshot of what it looks like now.

Many thanks.

![panel](https://user-images.githubusercontent.com/62569465/78353928-d829ef00-75a2-11ea-8d79-062aa44454da.png)

**Comment by LaMpiR** [comment]
Check the Changelog:
https://github.com/liaralabs/swizzin/blob/master/CHANGELOG.md

**Comment by Fuzzydroid** [comment]
> Check the Changelog:
> https://github.com/liaralabs/swizzin/blob/master/CHANGELOG.md

Oh, that explains it. Thank you.
