### ISSUE TITLE
 help new panel

### ISSUE THREAD

**Issue by foxan54** [liaralabs/swizzin#275]
Hi. 
I could use some help with the new panel. 
with the old panel I had modified the etc/nginx/app/panel.conf to work on xx.xx.xx.xx/panel because i use organizr on xx.xx.xx.xx 
I can't do the same with the new panel.

Someone can help me ? 
sorry for my english i'm learning english

**Comment by amil25** [comment]
you can use this commend 

box upgrade panel

**Comment by foxan54** [comment]
hi this doesn't work I would like to go to the panel by xx.xx.xx.xx.xx/panel

**Comment by WAELDIAB** [comment]
Have you updated the panel to the last version?

**Comment by foxan54** [comment]
i have got the new panel (swizzin panel) it works very well
/etc/nginx/apps/panel
[spoiler]
`location / {
  #rewrite ^/panel/(.*) /$1 break;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Host $host;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header Origin "";
  proxy_pass http://127.0.0.1:8333;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "Upgrade";
}
` [/spoiler]

I've been trying with
[spoiler]
`location /panel {
  #rewrite ^/panel/(.*) /$1 break;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Host $host;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header Origin "";
  proxy_pass http://127.0.0.1:8333;
  proxy_http_version 1.1;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Connection "Upgrade";
}` [/spoiler]

I don't know how to do it and I'm pretty bad at it.

**Comment by liaralabs** [comment]
There is not yet support for a base url in the application itself. It's coming soon, but not there yet.

When added, it will be an option in the application configuration.
