### ISSUE TITLE
Your Disk Status widget points to / instead of /home

### ISSUE THREAD

**Issue by tfp1** [liaralabs/swizzin#28]
Could be an OVH specific issue, but I don't see an obvious way to configure which disk is used for this widget

**Comment by liaralabs** [comment]
`box panel fix-disk home`

**Comment by tfp1** [comment]
> cp: cannot stat '/srv/panel/themes/defaulted/widgets/disk_datah.php': No such file or directory
> cp: cannot stat '/srv/panel/themes/smoked/widgets/disk_datah.php': No such file or directory

The only place I see the `disk_datah.php` file in /srv/panel/widgets.

**Comment by liaralabs** [comment]
Oh right, the refactor of quickbox_dashboard removed those files -- I need to devise a fix

**Comment by tfp1** [comment]
For now, I manually copied `disk_datah.php` --> `disk_data.php` and it's working just fine

**Comment by nandu2u2** [comment]
I have this same issue. What is the fix exactly?
