### ISSUE TITLE
filebrowser Wrong credentials

### ISSUE THREAD

**Issue by majeko1** [liaralabs/swizzin#283]
when i log into filebrowser ,give me message says Wrong credentials

i remove filebrowser and install again ,same problem

**Comment by userdocs** [comment]
It uses the user name and password in you master file in the root home directory

**Comment by majeko1** [comment]
> It uses the user name and password in you master file in the root home directory

how to  fix it ?

**Comment by liaralabs** [comment]
By using the username and password that are in the .master.info file in `/root/.master.info`
