### ISSUE TITLE
domain not working

### ISSUE THREAD

**Issue by bumjrah** [liaralabs/swizzin#30]
When I try reach seedbox through domain I get this error message: "DNS_PROBE_FINISHED_NXDOMAIN".

But when I type in the IP address I can access the panel. N

**Comment by liaralabs** [comment]
DNS_PROBE_FINISHED_NXDOMAIN means the DNS lookup failed in Chrome. As a DNS error this doesn't have anything to do with swizzin and is a local caching or DNS issue.

- Check the DNS is pointing to the right IP
- Wait to ensure the IP has had time to propagate through the network
- Try a browser other than Chrome
- Check/change your local DNS server (router or OS level)
- If all else fails, there are plenty of recommendations regarding how to fix this exact issue if you Google the error

**Comment by bumjrah** [comment]
Thank you. Seems my domain provider decided to cut off my domain name.
