### ISSUE TITLE
box upgrade curl not working correctly.

### ISSUE THREAD

**Issue by Magsamm** [liaralabs/swizzin#302]
The `box upgrade curl` command crashes

**To Reproduce**
1. run `box upgrade curl`
2. crash

**Expected behavior**
A working curl upgrade

**Server Info (please complete the following information):**
 - OS: Debian 10

**Additional context**
The following is printed in the terminal:
`/usr/local/bin/swizzin/upgrade/curl.sh: line 13: syntax error near unexpected token }'
/usr/local/bin/swizzin/upgrade/curl.sh: line 13: ./configure --enable-versioned-symbols >> ${log} 2>&1  { echo "There was an error configuring curl! Please check the log for more info"; cd /tmp; rm -rf curl*; exit 1; }'`

**Comment by flying-sausages** [comment]
https://github.com/liaralabs/swizzin/blob/master/scripts/upgrade/curl.sh#L13-L14
missing the `||`

**Comment by flying-sausages** [comment]
Should be fixed with b00f13f040fb7041cd00833f488b593c166ec5d8

Can you try `box update` and then `box upgrade curl` again?

**Comment by flying-sausages** [comment]
User confirmed working, can be closed
