### ISSUE TITLE
Adding ruTorrent-theme

### ISSUE THREAD

**Issue by exetico** [liaralabs/swizzin#31]
Hi'

I'm the dev. of FlatUO ruTorrent-theme, and would like to see the theme in the collection.

Will you be able to add it to the rutorrent.sh-script in the nginx-bin? It would be awesome!
I've a script you can call with:
`sh -c "$(curl -fsSL https://raw.githubusercontent.com/exetico/FlatUI/master/install.sh)"`
But feel free to to is in you own way.
https://github.com/exetico/FlatUI

Thanks!

**Comment by liaralabs** [comment]
Thanks for the suggestion! The repo is in a feature freeze at the moment, but I will take a look into adding this at a slightly later date once all the bugs are worked out of the installation :smile:

**Comment by liaralabs** [comment]
`rtx` is now in the development branch, where users can specify plugins/themes to add and remove. FlatUI has been included.

Once the feature is ready for prime time, I'll move it from devel to master.
