### ISSUE TITLE
NZBHydra wont install/start

### ISSUE THREAD

**Issue by nickp27** [liaralabs/swizzin#311]
After the recent updates, NZBHydra was not working so I removed and sought to reinstall.

I now get an error when using box install NZBHydra:

sed: can't read /home/*user*/.config/nzbhydra/settings.cfg: No such file or directory

The install completes but systemd fails to start.

**Comment by flying-sausages** [comment]
@nickp27 please run `box update` and then reinstall it through box. Sorry for the issues!
