### ISSUE TITLE
Change rutorrent screenshots plugin to save to .tar and not create an image collage

### ISSUE THREAD

**Issue by LastReaction** [liaralabs/swizzin#325]
It seems that the rutorrent screenshots plugin is currently set to create a collage of images all merged into one image, instead of a compressed tar file with individual screenshots saved within. How would I go about changing this? I've been digging through the screenshots plugin folder to find clues and so far, no luck. It doesn't look like changing the screenshots settings in rutorrent makes a difference either.

**Comment by flying-sausages** [comment]
1) Please follow the template
2) This seems like an issue with the actual rutorrent plugin itself and not the swizzin installer.
3) The Screenshots plug in does not seem to have config options for that https://github.com/Novik/ruTorrent/blob/master/plugins/screenshots/conf.php

**Comment by liaralabs** [comment]
Closing as this issue is not relevant to swizzin.

Consider using ffmpeg directly on the command line for more flexibility or devising your own script to automate your flow.
