### ISSUE TITLE
Swizzin possibly crashing server

### ISSUE THREAD

**Issue by Evoley** [liaralabs/swizzin#326]
## Bug description
Ever since a week and a half ago or longer.. my server seems to crash with swizzin installed. I'm not really sure why but I've never had more than a day up time. It's not the hardware as I've checked with Hetzner and everything seems to be ok. at least according to them. I'm willing to provide any more info (if I'm even able to) to this

## Reproduction steps
1. Install package nginx, letsencrypt (from certbot's PPA), rtorrent, rutorrent, vsftpd, bbr ( https://www.linuxbabe.com/ubuntu/enable-google-tcp-bbr-ubuntu )
2. wait a bit
3. Server should crash

## Installed applications through swizzin
 Nginx, rtorrent, rutorrent, vsftpd

## Expected behavior
Have more than a day of up time.

## Server Info
**(please complete the following information):**
 - OS: Ubuntu 18.04
 - Image Source: Installscript from my provider Hetzner

## Is Swizzin up to date?
- yes

- Please mention the commit hash you are seeing
  - HEAD is now at 43a002f Fix killing of irssi with deluser

## Additional context
Add any other context about the problem here. Logs, terminal output, etc.

Good sources for log output could be the following: (only if they have relevant information)
[vsftpd.log](https://github.com/liaralabs/swizzin/files/4625196/vsftpd.log)
[rtorrent.log](https://github.com/liaralabs/swizzin/files/4625197/rtorrent.log)
[nginx.log](https://github.com/liaralabs/swizzin/files/4625198/nginx.log)
[journalctl.log](https://github.com/liaralabs/swizzin/files/4625199/journalctl.log)
[error.log](https://github.com/liaralabs/swizzin/files/4625200/error.log)
[error2.log](https://github.com/liaralabs/swizzin/files/4625201/error2.log)

**Comment by flying-sausages** [comment]
I can't tell much from these logs except that there is something wrong with your rutorrent installation, as it is absolutely hammering the nginx error log. Did you install quota?

I'd try to reinstall rutorrent to see if this will make things run better.

**Comment by flying-sausages** [comment]
What specs does your machine have?

**Comment by liaralabs** [comment]
Yeah, I was going to mention the dmesg/kernel logs are going to be most helpful in diagnosing the exact reason why the server is going down as it's likely a kernel panic of some sort.

On the subject of kernels, what kernel are you currently running? (`uname -a`)

Finally, despite hetzner's claim that the hardware is fine, I wouldn't be surprised if this was a hardware issue with RAM. If you can figure out how to run a few passes with memtest86 on the server it would help rule out potential hardware related issues.

**Comment by Evoley** [comment]
> I can't tell much from these logs except that there is something wrong with your rutorrent installation, as it is absolutely hammering the nginx error log. Did you install quota?

Yeah, I installed quota. Nginx logs are really nothing new. IIrc i actually created a issue about this years ago.

> What specs does your machine have? Might be good to cross-check your RAM/CPU load. Also, check if there is anything in `/var/log` on the notes of `kern`, `kernel`, `syslog` and `dmesg`. Might want to read those yourself, and focus on the times when the server is horking.

i7 3770 with 32 GB of ram. 7x HDD SATA 4,0 TB . I'll have to run a system check when I get home. 
Here's syslog and kern.log.
[syslog.log](https://github.com/liaralabs/swizzin/files/4631545/syslog.log)
[syslog2.log](https://github.com/liaralabs/swizzin/files/4631546/syslog2.log)
[kern.log](https://github.com/liaralabs/swizzin/files/4631547/kern.log)
[dmesg.log](https://github.com/liaralabs/swizzin/files/4631581/dmesg.log)


> Yeah, I was going to mention the dmesg/kernel logs are going to be most helpful in diagnosing the exact reason why the server is going down as it's likely a kernel panic of some sort.
> 
> On the subject of kernels, what kernel are you currently running? (`uname -a`)
> 
> Finally, despite hetzner's claim that the hardware is fine, I wouldn't be surprised if this was a hardware issue with RAM. If you can figure out how to run a few passes with memtest86 on the server it would help rule out potential hardware related issues.

4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux. Hetzner actually changed my hardware about 2 or 3 times in trying to figure this out. The first time this happened I couldn't even log into ssh or any kind of connection after a restart I couldn't even activate the rescue system. The 2nd time I noticed that something (not sure what) was editing sshd_config and adding port 222. Wasn't able to connect then. The 3rd time (now) it somehow works except for the crashing at random times.

**Comment by flying-sausages** [comment]
Might be useful to give us a time and date for when you noticed things went down, given your plaintext logs are like over 2MBs ;)
I can assure you nothing from swiz would touch your ssh config at the time of writing.

**Comment by Evoley** [comment]
Unfortunately I can't really give a precise time as it happens when I'm sleeping or at work.

**Comment by flying-sausages** [comment]
Well, that's sadly not going to make this easier for anyone. There are way over a hundred thousand lines of logs you submitted and I don't know what to look for or at what times. I would suggest giving another reinstall a shot, not installing swizzin on it, and doing some basic benchmarking/folding@home, and making some sort of an uptime status report through something like uptime robot so you get the times of when things break. Might as well install 20.04 if you're looking at keeping this box for longer than 3 years. If all goes well for a two days or so, try installing swizzin on it, and see if it starts breaking. I would generally suggest using a vanilla, uncustomised installation as well, I know Hetzner adds a bunch of stuff to their images and this would further rule out some 4th party issues. We also have a swizzin troubleshooting guide on docs.swizzin.ltd where you can give some of the steps a shot. Feel free to join the discord and the #ce-community-help room.
