### ISSUE TITLE
Jackett is installed in ~/ instead of /opt/

### ISSUE THREAD

**Issue by varoOP** [liaralabs/swizzin#329]

**Comment by flying-sausages** [comment]
Yeah this should be moved eventually. I looked at the code and I'm personally not too interested in fixing this, maybe someone else will make a PR for this eventually.

**Comment by flying-sausages** [comment]
when #343 is closed I'll do the same thing to Jackett

**Comment by flying-sausages** [comment]
Still an issue last time i checked
