### ISSUE TITLE
Blank page on Flood after new install

### ISSUE THREAD

**Issue by MatiWal** [liaralabs/swizzin#33]
Running on Debian 9. Chose Flood as the interface to rtorrent. Panel works properly, but clicking Flood brings up a new blank tab.

**Comment by liaralabs** [comment]
I'm working on narrowing down why exactly this is happening at the moment. The install seems to require `npm install && npm build` to be run twice at the moment.

A workaround until I can get a fix implemented is to simply run the command `box upgrade flood` if you are facing the white screen

**Comment by MatiWal** [comment]
Hrm. New issue. I'm familiar with Box, but I'm getting command not found when I run it

**Comment by liaralabs** [comment]
Please ensure you have either restarted your SSH session or reloaded .profile with `source /root/.profile` before running box commands
