### ISSUE TITLE
Webmin gets error 504 when uploading/compressing large files.

### ISSUE THREAD

**Issue by varoOP** [liaralabs/swizzin#332]
## Bug description
Webmin gets error 504 when uploading/compressing large files. 

## Reproduction steps
1. Install Webmin [box install webmin]
2. Go to host.com/webmin
3. Login with master user. 
4. Compress 50 gig folder to tar.gz using file manager. 
5. Error : 504

## Installed applications through swizzin
 Nginx, ffmpeg, panel,radarr,rutorrent,filebrowser,znc,webmin

## Expected behavior
For the folder to get compressed and leave a *tar.gz.
## Server Info
**(please complete the following information):**
 - OS: Debian 10
 - Image Source: Vanilla Download

## Is Swizzin up to date?
HEAD is now at 65f8719 updated css aesthetics to address overlapping
Already up to date.

**Comment by flying-sausages** [comment]
Please follow the template.

**Comment by varoOP** [comment]
I am sorry, I don't understand. Which template?

**Comment by liaralabs** [comment]
When you opened your issue, you ignored the [bug report template](https://github.com/liaralabs/swizzin/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)

**Comment by varoOP** [comment]
I have updated it following the template now. 
Sorry for that!

**Comment by flying-sausages** [comment]
Can you upload any logs? Try reproduce it, mark the time, and upload the related lines in `/var/webmin/webmin.log.`

Swizzin manages the configuration of the proxy that redirect you from .../webmin to ...:10000. It does not however play with any of the webmin code or config that would impact it in this regard.

Uploading these logs will most likely verify my assumption that this is a webmin-side bug, and might be better to report in the webmin repository. But you never know... Knowing their structure is made of many different modules, I would see if there is a specific project/repo/contact for the File Manager.

**Comment by varoOP** [comment]
https://easycloudsupport.zendesk.com/hc/en-us/articles/360002057472-How-to-Fix-504-Gateway-Timeout-using-Nginx  
Following the steps here has fixed the issue!
