### ISSUE TITLE
How to open a port

### ISSUE THREAD

**Issue by cola32** [liaralabs/swizzin#333]
Hi,
how can I open a port?
I want to install for example Teamspeak on my sever.
But after the installation I can’t reach the server. (port 9987)
Are all ports are blocked ?

**Comment by flying-sausages** [comment]
No, your machine's ports are not firewalled. Please consult this guide. https://docs.swizzin.ltd/guides/troubleshooting#accessing-a-home-hosted-swizzin-installation-externally

**Comment by cola32** [comment]
Ok thanks 
Then something in my configuration should be wrong

**Comment by foxan54** [comment]
i use teamspeak with my swizzin server this tuto is ok for me.
https://mondedie.fr/d/5890-tuto-installation-de-teamspeak-3

Sorry it's a french tuto and he have a problem in the "nano /etc/init.d/teamspeak" it's just the name DIR that you need to fix.
But the web interface he doesn't work for me 

sorry about my english i am learning it ^^'
