### ISSUE TITLE
jellefyn doesn't work

### ISSUE THREAD

**Issue by riptide981** [liaralabs/swizzin#335]
# jellyfin doesn't work

## Bug description
Open https://ip/jellyfin/ (directly or from panel) gets an "Invalid host" error.

## Reproduction steps
1. Install package: box install jellyfin
2. Go to: https://ip/jellyfin/ (directly or from panel)
3. Error: "Invalid host"

## Installed applications through swizzin
Nginx, panel, flood, rtorrent, jellyfin

## Expected behavior
Get the jellyfin landing page.

## Server Info
 - OS: OpenMediaVault (Debian 10)
 - Image Source: openmediavault_5.3.9-amd64.iso

## Is Swizzin up to date?
Yes, hash: b4f59c8

## Solution

1.- edit /etc/nginx/apps/jellyfin.conf line 6 from:

`    proxy_set_header Host $host;`

to
 
`    proxy_set_header Host $hostname;`

2.- execute: `sudo systemctl reload nginx`
3.- ...
4.- profit

## Speculation

Maybe some error with the hostname funtion. nginx ssl config doesn't work correctly when installed. I don't remenber the exac behaviour.

Edit: typos

**Comment by liaralabs** [comment]
What is the value of your `server_name` in your default nginx config? Is it something a bit funky/non-standard?

**Comment by riptide981** [comment]
> What is the value of your `server_name` in your default nginx config? Is it something a bit funky/non-standard?

Originally it was   `server_name _;`, i manually change it to `  server_name nas-test;` to workarround an ssl problem with the hostname.

> OpenMediaVault is not something that has been directly tested -- there may be modifications to the debian core that are causing these sorts of issues otherwise

Maybe the OMV people made some "weird" stuff with the 'hostname' handling
