### ISSUE TITLE
Hard drive

### ISSUE THREAD

**Issue by supershaun** [liaralabs/swizzin#34]
Hi 

ive previously installed swizzin but for some reason my dedicated server which has 6tb is only showing 1000gb on panel and 1.6tb on rutorrent any ideas.Please see below images

Thanks
![rtorrent](https://user-images.githubusercontent.com/33321032/32328661-92bcddb6-bfd2-11e7-9d2a-51b293cd31b5.png)
![hetzner](https://user-images.githubusercontent.com/33321032/32328668-95cb4858-bfd2-11e7-9677-905aa05c6ff6.png)

**Comment by Vach0n** [comment]
I have the same server as you with Hetzner... You need to setup the RAID 0 correctly when setting up the server.

Try and do the following from scratch:

> 1. Log into Hetzner Robot and activate "Rescue System" and reboot the server.
> 2. SSH into your newly activated Rescue System.
> 3. Type `installimage` and choose `Ubuntu` and then `Ubuntu 16.04 - Minimal`.
> 4. Now ensure in the config here, that you set `SWRAID = 1` and `SWRAIDLEVEL = 0`.
> 5. Almost at the end of the config, delete `PART /home ext4 all`.
> 6. Change `/ ext3 1024G` to `/ ext3 all`.
> 7. Press F10, save the config, complete the install and reboot the server.
> 8. SSH into the newly installed Ubuntu server and install swizzin and you should be good to go.

I hope this helps you.

/Vach0n

**Comment by supershaun** [comment]
will try it and let you know and thanks for fast response

**Comment by Vach0n** [comment]
No problem.
Please keep us posted, if my information above worked for you :)

**Comment by supershaun** [comment]
no hasnt worked for me same size drive

**Comment by Vach0n** [comment]
Can you do `df -h` in terminal and post a pastebin of the results?

**Comment by supershaun** [comment]
okay

**Comment by supershaun** [comment]
this what shows

* Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage
Last login: Fri Nov  3 00:24:18 2017 from 82.13.198.41
root@Ubuntu-1604-xenial-64-minimal ~ # df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.8G     0  7.8G   0% /dev
tmpfs           1.6G   13M  1.6G   1% /run
/dev/md1       1008G  2.0G  955G   1% /
tmpfs           7.8G     0  7.8G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
/dev/md2        2.2T  130M  2.1T   1% /boot
tmpfs           1.6G     0  1.6G   0% /run/user/0
root@Ubuntu-1604-xenial-64-minimal ~ #

**Comment by supershaun** [comment]
ive fixed it was setup wrong had a look on quickbox website instead

**Comment by liaralabs** [comment]
Great! Glad to hear you got it sorted. I'll be closing the issue as it seems to be resolved.
