### ISSUE TITLE
doesn't load

### ISSUE THREAD

**Issue by goodpunk6** [liaralabs/swizzin#35]
My install finished but I can't reach anything. Meaning, I type my vps IP into my browser, and I get This site can't be reached. I can reach any other site on the internet except for this one. 

So I can't reach the panel/nothing else, and the list of ports aren't listed anywhere. Help!

**Comment by liaralabs** [comment]
Is nginx installed? If so, most of the endpoints are basically the app name:

https://IP/rutorrent
https://IP/flood
https://IP/sickrage
etc..

Without the panel installed https://IP should lead to a 403 forbidden page.

If nginx is not installed, the endpoints are simply the default ports in just about all cases. You may need to check the documentation of each specific app if you're not familiar with it.

I admit these things could be better documented in the wiki (which is publicly editable!), but I've been too busy to work on documentation.

**Comment by goodpunk6** [comment]
awesome stuff! I did not install nginx but I will now. remembering the name of the service is easier than the port. I was able to reach couchpotato on the default port. Yay!
