### ISSUE TITLE
tcp port 80 is already used

### ISSUE THREAD

**Issue by skurty** [liaralabs/swizzin#352]
## Bug description
Letsencrypt domains not renewed

## Reproduction steps
1. Install a letsencrypt domain
2. Login as root
3. Run the contab job: "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh"
4. Error:
```
[Mon Jun 22 09:50:59 CEST 2020] ===Starting cron===
[Mon Jun 22 09:50:59 CEST 2020] Renew: 'XXX'
[Mon Jun 22 09:51:00 CEST 2020] Standalone mode.
[Mon Jun 22 09:51:00 CEST 2020] LISTEN   0         128                 0.0.0.0:80               0.0.0.0:*        users:(("nginx",pid=17628,fd=12),("nginx",pid=17627,fd=12),("nginx",pid=1572,fd=12))
LISTEN   0         128                    [::]:80                  [::]:*        users:(("nginx",pid=17628,fd=13),("nginx",pid=17627,fd=13),("nginx",pid=1572,fd=13))
[Mon Jun 22 09:51:00 CEST 2020] tcp port 80 is already used by (("nginx",pid=17628,fd=12),("nginx",pid=17627,fd=12),("nginx",pid=1572,fd=12))
80                  [
[Mon Jun 22 09:51:00 CEST 2020] Please stop it first
[Mon Jun 22 09:51:00 CEST 2020] _on_before_issue.
[Mon Jun 22 09:51:00 CEST 2020] Error renew XXX.
``` 

## Installed applications through swizzin
Nginx, Letsencrypt

## Expected behavior
The domain should be renewed

## Server Info
 - OS: Ubuntu 18.04
 - Image Source: Vanilla download

## Is Swizzin up to date?
Yes, current commit: 71d4420

**Comment by an0n666** [comment]
Also had same issue. Turns out you have to stop nginx process before running that script.

**Comment by flying-sausages** [comment]
> Also had same issue. Turns out you have to stop nginx process before running that script.

That should not be the intended behavior, the script should definitely interact with nginx so that it is passed through for the verification.

**Comment by flying-sausages** [comment]
@skurty did you install nginx before installing swizzin? I'd suggest to reinstall the swizzin nginx and then try doing the letsencrypt setup just to make sure your install is "up to spec".

**Comment by an0n666** [comment]
> > Also had same issue. Turns out you have to stop nginx process before running that script.
> 
> That should not be the intended behavior, the script should definitely interact with nginx so that it is passed through for the verification.

Yeah that’s definitely not intended but a bug. 
The script never auto renewed my certs and I figured it was because port 80 was occupied by nginx.

**Comment by liaralabs** [comment]
This is an unintended side-effect of choosing "no" when answer the question "apply to default config?"

When choosing no here, acme.sh goes into standalone mode which requires that nginx actually be stopped (hence nginx stopping before running in standalone). There may be a way to spruce this up a bit, but it may require adding a bit of complexity to the script.

That said, as long as you have current, valid nginx confs for these domains in question you should be able to change the mode of the renewal over to nginx manually, which will help solve the problem in the future.

Conf files are stored in:
```
/root/.acme.sh/domain.com
```

The file you need to edit is:
```
/root/.acme.sh/domain.com/domain.com.conf
```

Change the line:
```
Le_Webroot=*
```
to
```
Le_Webroot='nginx:'
```

And try a renewal with

```
acme.sh --renew -d domain.com
```

**Comment by liaralabs** [comment]
This has been fixed for future installs by making sure nginx is stopped and started using pre/post hooks with the issuance. Due to the nature of LE installs, it's unlikely that I will be issuing an update patch for current installs.

I believe you should be able to just re-run the lets encrypt installer for the domain and it should pickup the new changes.

Otherwise, if the pre/post hooks aren't updated after a re-issue you can remove your domain with acme.sh and then reinstall:

```
acme.sh --remove -d domain.com
box install letsencrypt
```
