### ISSUE TITLE
rtorrent failed to start (Could not prepare socket for listening: Permission denied)

### ISSUE THREAD

**Issue by amirulabu** [liaralabs/swizzin#359]
## Reproduction steps
rtorrent is not started when: 
- installed
- run `sudo systemctl restart rtorrent@$USER`
- run `rtorrent`

## Installed applications through swizzin
rtorrent

## Expected behavior
rtorrent started

## Server Info
**(please complete the following information):**
 - OS: Ubuntu 20.04
 - Image Source: Installscript from my provider (specify which)"]

## Is Swizzin up to date?
- yes

- Please mention the commit hash you are seeing
  - HEAD is now at 65f8719 updated css aesthetics to address overlapping

## Additional context
- the username i use during swizzin installation is `user` that may cause problem
- run `rtorrent` gives out this error 
```
rtorrent: Error in option file: ~/.rtorrent.rc:9: Could not prepare socket for listening: Permission denied
```

**Comment by flying-sausages** [comment]
Please check the rtorrent troubleshooting chapter on the docs website.

**Comment by liaralabs** [comment]
What is line 9 of `~/rtorrent.rc`?

**Comment by amirulabu** [comment]
> What is line 9 of `~/rtorrent.rc`?

`network.scgi.open_local = /var/run/${user}/.rtorrent.sock`

https://github.com/liaralabs/swizzin/blob/d20a56f41c1f47ff35a242695471c371d89fe8bb/scripts/install/rtorrent.sh#L24

**Comment by liaralabs** [comment]
Did you paste this in directly? There's little reason the variable shouldn't have expanded.

The line should read:

```
network.scgi.open_local = /var/run/user/.rtorrent.sock
```

**Comment by amirulabu** [comment]
so i have reinstalled the OS and do another swizzin install with a different username, (not `user`) and rtorrent works as normal

**Comment by s1p2a3m** [comment]
In case anyone stumbles upon this, my issue was the folder did not exist `/var/run/${user}`
After creating it I was still getting the permission denied error... I had to `sudo chown appbox:appbox /var/run/${user}` and afterwards it finally worked (where ${user} your user)
