### ISSUE TITLE
Couchpotato redirect to Swizzin Dashboard

### ISSUE THREAD

**Issue by earendildev** [liaralabs/swizzin#360]
**Expected Behavior**
Once Couchpotato is installed, go to Browser URL = _http(s)://_yourip_/couchpotato_ and go through the wizard.

**What Happened**
Once installed, clicking on the Couchpotato option on the Swizzin Dashboard, opens a new browser with the URL = _http://_yourip_/#couchpotato_ and redirects to swizzin Dashboard.

This happened the second time I installed Swizzin on a new server. The first time I installed swizzin, this issue didn't happen.
The only difference between the two servers was the SWAP file. 
The first server had the SWAP file increased before the Swizzin install, while the second server had the SWAP file increase after the Swizzin install.

**Solution**
I noticed that the redirect was happening due to the `url base =` within the Couchpotato _settings.conf_ file was empty.
To fix it, I added `url base = /couchpotato`
After that I did a restart of the Couchpotato service `sudo systemctl restart couchpotato`

It would be great if this solution could be added to the Couchpotato section of the Troubleshooting guide.

**Comment by flying-sausages** [comment]
Did you install nginx after couchpotato?

**Comment by flying-sausages** [comment]
Looks like it should have been regardless. https://github.com/liaralabs/swizzin/blob/master/scripts/nginx/couchpotato.sh#L26 I wonder if the `sed` executes succesfully. Chance also is that the config might be overwritten if couchpotat gets shut down after the `sed` is executed.

**Comment by liaralabs** [comment]
The `sed` does execute correctly -- otherwise the wizard never would have showed up and the redirects would have started immediately.

Is there a possibility that you removed the baseurl during setup of the wizard?

**Comment by earendildev** [comment]
> Did you install nginx after couchpotato?

Not really. I followed the step-by-step automatic installation, pretty much self explanatory and outlined in the documentation. 
To answer your question, no. Couchpotato was installed after Nginx, as per the installer.

**Comment by earendildev** [comment]
> Is there a possibility that you removed the baseurl during setup of the wizard?

Not really no. I made sure to follow the step by step guide.

If you would like to close this issue, that's fine.
I just wanted to be sure that you include this solution in the Couchpotato section of the documentation, incase anyone comes across a similar issue.

**Comment by flying-sausages** [comment]
I suppose a more convenient thing to do would be to refer closed GitHub issues as a form of troubleshooting in the big guide. This seems like an odd edge case that will not happen again. If I'm proven wrong I'll eat my hand and add it to the docs ;)

**Comment by earendildev** [comment]
hahaha

> I suppose a more convenient thing to do would be to refer closed GitHub issues as a form of troubleshooting in the big guide. This seems like an odd edge case that will not happen again. If I'm proven wrong I'll eat my hand and add it to the docs ;)

Haha, That's true. Doubt it would happen again.
Just thought I would mention it.
To be fair, I was testing this out on GCP's servers before provisioning it out on my local server.

Thanks for the help though @flying-sausages
