### ISSUE TITLE
Deluge. The password isn't correct. Can't reset it

### ISSUE THREAD

**Issue by Niggabruh** [liaralabs/swizzin#366]
Ubuntu 20.04. Kernel 5.4.0-40

When the installation finished, then I can't login into Deluge. Can't reset password too.
I noticed these lines during the installation:

```
E: Unable to locate package python-libtorrent
Building Deluge
cp: cannot create regular file '/usr/lib/python2.7/dist-packages/deluge/ui/console/commands/update-tracker.py': No such file or directory
Configuring Deluge
```
Any idea how to fix it?

Looks like a week ago everything was just okay, no problem

Thank you

**Comment by Niggabruh** [comment]
Transmission isn't working too. Just 502 bad gateway. Tried from root and from just user. Nothing changed. Fix it please guys.

**Comment by flying-sausages** [comment]
Create a new issue and follow the template.

**Comment by liaralabs** [comment]
Please re-open issues using the issue template and provide the requested information
