### ISSUE TITLE
Bandwidth consumption

### ISSUE THREAD

**Issue by Niggabruh** [liaralabs/swizzin#367]
Just turned off everything in the panel, t=but the system consumes ~120-150 megabytes every hour in idle mode. It's ~3GB per day and around 90-100GB per month for just nothing. I have an idle VPS but it doesn't consume so much bandwidth. So I think the problem is on swizzin side. Where this traffic goes and how to stop it?

![ba](https://user-images.githubusercontent.com/68474750/87867525-6da48f80-c996-11ea-97d7-98701b28233b.png)

**Comment by flying-sausages** [comment]
Create a new issue and follow the template.

**Comment by liaralabs** [comment]
Please re-open issues using the issue template and provide the requested information
