### ISSUE TITLE
ruTorrent doesn't upgrade to latest version

### ISSUE THREAD

**Issue by an0n666** [liaralabs/swizzin#376]
## Bug description
I had rutorrent 3.9 installed and after running box upgrade rutorrent it still remained 3.9 whereas the latest release is 3.10

## Reproduction steps
1. Install package '...' rutorrent
2. Go to '....' box upgrade rutorrent
3. Error '...' not upgraded

## Installed applications through swizzin
(e.g. Nginx, ffmpeg, panel)
rutorrent
## Expected behavior
(A clear and concise description of what you expected to happen.)
upgrade rutorrent properly.
## Server Info
**(please complete the following information):**
 - OS: (e.g. Debian 10, Ubuntu 20.04)
 - Image Source: (e.g. "Vanilla download" or "Installscript from specific provider")
ubuntu 18.04
## Is Swizzin up to date?
(Please run `box update`, and report whether that was succesful. Please try to reproduce your issue) again. mention the commit hash you are seeing)
yes
(e.g. HEAD is now at d4d151b)

## Additional context
(Add any other context about the problem here. Logs, terminal output, etc.)
Nothing relevant found in logs.
(Good sources for log output could be the following: (only if they have relevant information))
- `cat /root/logs/install.log`
- `cat /root/logs/swizzin.log`
- `cat /var/logs/nginx/error.log`
- `systemctl status <app>@<(user)>`
- `journalctl -xe`

**(Please paste your code into code blocks using the codeblock format like below)**

(For logs of 50+ lines, please rehost to a paste hoster like 0bin)

 ```
 ... logs ...
 ```

**Comment by liaralabs** [comment]
There is no ruTorrent upgrade method that is deemed stable and there is no dev-supported method of upgrading ruTorrent either.

There is an upgrade script in the dev repository, but it's use at your own risk and entirely unsupported.

https://github.com/liaralabs/swizzin/blob/devel/scripts/upgrade/rutorrent.sh
