### ISSUE TITLE
Install Script "APT-GET Error" if Ipv6 is disable

### ISSUE THREAD

**Issue by BoNxEr** [liaralabs/swizzin#379]
## Bug description
My server have ipv6 disabled by default. If i try to install the script without ipv6 , i receive APT-GET ERROR for install nginx and others. But all good when ipv6 is active.

## Reproduction steps
1. Fresh install
2. disable ipv6
3. APT-GET error after launch the script

## Installed applications through swizzin
Nginx, rtorrent, rutorrent, autodl, ffmpeg

## Expected behavior
I dont use ipv6 and i want install script without ipv6 active

## Server Info
**(please complete the following information):**
 - OS: Debian 10.5

**Comment by flying-sausages** [comment]
Sounds like your APT is misconfigured. See what happens when you test your apt directly.

**Comment by BoNxEr** [comment]
> Sounds like your APT is misconfigured. See what happens when you test your apt directly.

it seem apt-get install not work but APT install work...
