### ISSUE TITLE
Python issue at install

### ISSUE THREAD

**Issue by Nico83500** [liaralabs/swizzin#385]
## Bug description
During install, I get 2 python errors : 
```
Using php7.4-fpm in the nginx config
Restarting php7.4-fpm.service
Installing rtorrent
Installing rTorrent Dependencies ...
Installing rtorrent with apt-get ...
Making nicolas directory structure ...
setting up rtorrent.rc ...
Installing rutorrent
Restarting php7.4-fpm.service
Installing deluge
Building libtorrent-rasterbar
Reading package lists...
Building dependency tree...
Reading state information...
**_E: Unable to locate package python-libtorrent_**
Building Deluge
**_cp: cannot create regular file '/usr/lib/python2.7/dist-packages/deluge/ui/console/commands/update-tracker.py': No such file or directory_**
Configuring Deluge
```

## Reproduction steps
Launch the setup command line

## Installed applications through swizzin
Nginx, rtorrent, deluge, autodl, panel, vsftpd, ffmpeg, quota

## Expected behavior
No python error at install

## Server Info
**(please complete the following information):**
 - OS: Ubuntu 20.04
- Image Source: Dedicated server

## Is Swizzin up to date?
Yes

(e.g. HEAD is now at d4d151b)

## Additional context
None

**Comment by liaralabs** [comment]
Can you please provide more info surrounding the context of your Deluge/libtorrent installation?

i.e. for Deluge: repo, 1.3.15 or v2 and for libtorrent: repo, rc_1_1 or rc_1_2

**Comment by liaralabs** [comment]
Closing due to:

- lack of info
- likely fixed in recent deluge commits (will not cp update-tracker.py when not installing Deluge 1.3)
