### ISSUE TITLE
Can't upgrade SABnzbd

### ISSUE THREAD

**Issue by ciasis** [liaralabs/swizzin#387]
## Bug description
I want to upgrade SABnzbd from my local version 2.3.9 to the latest (3.0.2) via the command _box upgrade sabnzbd_, but this doesn't work. It produces this error:

![sab](https://user-images.githubusercontent.com/50784424/91825024-f8d29f80-ec3b-11ea-8c43-7ed8d0738c01.JPG)

## Reproduction steps
1. Just run _box upgrade sabnzbd_ and it will fail (I guess).

## Installed applications through swizzin
Nginx, ffmpeg, panel, Deluge, rTorrent & ruTorrent; Radarr, Jackett, NZBHydra2

## Expected behavior
I expect the box to upgrade SABnzbd, nothing more :-)

## Server Info
**(please complete the following information):**
 - OS: Debian GNU/Linux 10 (buster)
 - Kernel: Linux version 5.7.0-10.1-liquorix-amd64 (steven@liquorix.net) (gcc version 8.3.0 (Debian 8.3.0-6), GNU ld (GNU Binutils for Debian) 2.31.1) #1 ZEN SMP PREEMPT liquorix 5.7-14.1~buster (2020-07-23)

## Is Swizzin up to date?
Yes, I just did _box update_ :-)

## Additional context
I think(!) that it has something to do with the upgrade code. Based on the error I guess the comparison of the local and the remote version fails.

**Comment by liaralabs** [comment]
There was a typo in the path of the venv for sabnzbd (`/opt/sabnzbd/venv` when it should be `/opt/.venv/sabnzbd`).

I've just rectified this typo in the repo. Can you try running `box upgrade sabnzbd` again and report back?

**Comment by ciasis** [comment]
So first, I ran `box update` and then, I ran `box upgrade sabnzbd`. This was the outcome:

![Unbenannt](https://user-images.githubusercontent.com/50784424/92453455-917a9980-f1bf-11ea-8d3a-2023075391e7.JPG)

**Comment by liaralabs** [comment]
Somehow the commit got reverted (may have happened during a PR merge the same day), please try again :)

**Comment by liaralabs** [comment]
Relevant commits since I don't know what happened to the one I previously mentioned:
50368480f8d61140bee8332785b2afddd73fc139
e3d75f54b2034c447835296b9038a162a028acfa

**Comment by ciasis** [comment]
That worked! I'm finally on 3.0.2 :-) 

Thank you a lot, liara, great work! Have a great day!
