### ISSUE TITLE
How to update filebrowser?

### ISSUE THREAD

**Issue by LastReaction** [liaralabs/swizzin#389]
This isn't really an issue, I'm just wondering how I would go about properly updating the filebrowser application included with Swizzin. It's currently on 2.1.0 and the latest version is 2.6.2. If anyone could help here, that would be appreciated.

**Comment by liaralabs** [comment]
The FB update mechanism is known to be lacking at the moment; however, this sort of discussion would be much better suited for the discussion boards as this isn't really a bug:

https://github.com/liaralabs/swizzin/discussions
