### ISSUE TITLE
Adding Seafile

### ISSUE THREAD

**Issue by lattedesu** [liaralabs/swizzin#40]
Hello,

First of all, congrats on maintaining such a nice script!

I'd like to suggest [Seafile](https://www.seafile.com/en/home/) in addition to nextcloud.

Because, as a user who used both (and owncloud before), if you're only after file syncing, Seafile is a better choice in my opinion. Nextcloud is slower on my experience, doesn't have a real client side encryption, and still couldn't fix [this](https://github.com/nextcloud/client_theming/issues/13) for over a year. Also it has a delta sync feature which is quite useful.

Here are some discussions:
https://www.reddit.com/r/selfhosted/comments/69ghby/looking_for_a_dropbox_replacement_in_2017_seafile/
https://www.reddit.com/r/selfhosted/comments/6hqfec/seafile_vs_nextcloud/
https://www.reddit.com/r/selfhosted/comments/59wjro/what_reasons_to_use_nextcloud_over_seafile/

I'd appreciate if this could be considered in the future.

Thanks in advance,

**Comment by liaralabs** [comment]
I prefer Seacloud myself; however the installation is not nearly as straightforward. There are a lot of steps that can't really be automated, so scripting will take some consideration. It may be a while until this gets looked at.

**Comment by liaralabs** [comment]
Feature requests have moved to feathub, I've gone ahead and added it to the list.

Closing this issue
