### ISSUE TITLE
Ubuntu 20.4/Deluge

### ISSUE THREAD

**Issue by Bishop-trevorstuart** [liaralabs/swizzin#411]
Bug description
Using sudo box install deluge the following error appears
/usr/local/bin/swizzin/install/deluge.sh: line 28: python2: command not found

Reproduction steps

install deluge without installing python2

Expected behavior
don't require python2

Server Info
(please complete the following information):

OS: Ubuntu 20.04.1 LTS
Is Swizzin up to date? Yes

**Comment by liaralabs** [comment]
Can you tell me if you installed Deluge v2 or Deluge 1.3.15?

Admittedly the helper scripts are still based on python2 but you cannot avoid python2 if you wish to use Deluge 1.3.15.

Some fixes incoming shortly for the python issues

**Comment by Bishop-trevorstuart** [comment]
Deluge v2 was selected,

**Comment by liaralabs** [comment]
Closing this issue as it is fixed.
