### ISSUE TITLE
nginx fails to start after 'box update' due to fancy index

### ISSUE THREAD

**Issue by Clearshot13** [liaralabs/swizzin#421]
## Bug description
After running the `box update` command the nginx service fails to start due to fancy index.

## Reproduction steps
1. box update
2. nginx service fails to start after `box update`

## Installed applications through swizzin
nginx, panel, sonarr, radarr, jackett, plex, letsencrypt

## Expected behavior
nginx service to start successfully after `box update`

## Server Info
Ubuntu 16.04.7

## Is Swizzin up to date?
```
root@leon:~# box update
Updating swizzin local repository
Already on 'master'
Your branch is up-to-date with 'origin/master'.
remote: Enumerating objects: 34, done.
remote: Counting objects: 100% (34/34), done.
remote: Total 63 (delta 34), reused 34 (delta 34), pack-reused 29
Unpacking objects: 100% (63/63), done.
From https://github.com/liaralabs/swizzin
 * branch            master     -> FETCH_HEAD
   aa4915d..da0864a  master     -> origin/master
HEAD is now at da0864a Can't use apt-add-repository to remove defunct PPAs (#420)
ln: failed to create symbolic link '/etc/nginx/modules-enabled/50-mod-http-fancyindex.conf': File exists
grep: /srv/fancyindex/header.html: No such file or directory
grep: /srv/fancyindex/footer.html: No such file or directory
Restarting php7.0-fpm.service
nginx.service is not active, cannot reload.
Updating panel to latest version
Pulling new commits
Already up-to-date.
Restarting Panel
Done!
```

## Additional context
 ```
root@leon:~# systemctl status nginx.service
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2020-10-16 22:40:56 CEST; 6s ago
  Process: 8087 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)

Oct 16 22:40:56 leon systemd[1]: Starting A high performance web server and a reverse proxy server...
Oct 16 22:40:56 leon nginx[8087]: nginx: [emerg] unknown directive "fancyindex" in /etc/nginx/snippets/fancyindex.conf:1
Oct 16 22:40:56 leon nginx[8087]: nginx: configuration file /etc/nginx/nginx.conf test failed
Oct 16 22:40:56 leon systemd[1]: nginx.service: Control process exited, code=exited status=1
Oct 16 22:40:56 leon systemd[1]: Failed to start A high performance web server and a reverse proxy server.
Oct 16 22:40:56 leon systemd[1]: nginx.service: Unit entered failed state.
Oct 16 22:40:56 leon systemd[1]: nginx.service: Failed with result 'exit-code'.
 ```

**Comment by flying-sausages** [comment]
Can you please post the logs from swizzin?

**Comment by Clearshot13** [comment]
install.log
https://pastebin.com/vRifx7Yk

swizzin.log
https://pastebin.com/tyUS2WqH

**Comment by rjroot** [comment]
Same for fresh install on Ubuntu 20.04,Debian 10. After successful install website says: 500 Internal server error.
There is no error code however webpage does not load.

**Comment by liaralabs** [comment]
@rjroot can you please open a separate issue with logs and detailed info about the steps you took as your problems are completely different. This issue is about nginx not starting at all on Xenial. You are getting a 500 error which means nginx is started. 

@Clearshot13 can you please provide the output of `nginx -t`?

**Comment by Clearshot13** [comment]
Sorry, I should have mentioned I upgraded from 16.04.7 -> 20.04.1 shortly after opening this issue. This is what I've done the past few days to get out of this mess. It is by no means the proper solution but I'm back up and running until the issue is figured out.

started with Ubuntu 16.04.7
box update
nginx fails to start
do-release-upgrade to Ubuntu 18
fixed a ton of errors with services
nginx still failing due to fancy index
do-release-upgrade to Ubuntu 20
nginx still fails due to fancy index, to get nginx started again I disabled fancy index

/etc/nginx/snippets/fancyindex.conf
`
#fancyindex on;
#fancyindex_localtime on;
#fancyindex_exact_size off;
#fancyindex_header "/fancyindex/header.html";
#fancyindex_footer "/fancyindex/footer.html";
#fancyindex_ignore "examplefile.html"; # Ignored files will not show up in the directory listing, but will still be public. 
#fancyindex_ignore "Nginx-Fancyindex-Theme"; # Making sure folder where files are don't show up in the listing. 
#fancyindex_name_length 255; # Maximum file name length in bytes, change as you like.
`

**Comment by flying-sausages** [comment]
have you by any chance tried `box remove nginx` and `box install nginx`?

**Comment by Clearshot13** [comment]
No, I don't want to lose my nginx configurations. I have quite a few reverse proxies and other services configured within nginx.

**Comment by liaralabs** [comment]
Since you have release upgraded twice since the initial problem, it's tough to say what caused the issue anymore.

Regardless, you should be able to re-enable your fancyindex configuration if you

```
apt install libnginx-mod-http-fancyindex
```
And change your fancyindex config back to the default

**Comment by Clearshot13** [comment]
It worked! I also had to add `include /etc/nginx/modules-enabled/*.conf;` to the top of nginx.conf.

Thanks for your help
