### ISSUE TITLE
Libtorrent from repo

### ISSUE THREAD

**Issue by Nico83500** [liaralabs/swizzin#425]
Hi,
I'm reinstalling Swizzin but I have a warning from libtorrent choice :
`dpkg: warning: version 'repo' has bad syntax: version number does not start with digit
Defaulting to libtorrent branch RC_1_2 for compatibility`
So I can't choose the libtorrent version.
Is it normal ?
Thank you.

**Comment by liaralabs** [comment]
Please re-open the issue and take the time to use the issue template this time.
