### ISSUE TITLE
Can't choose the libtorrent version

### ISSUE THREAD

**Issue by Nico83500** [liaralabs/swizzin#427]
## Bug description
Can't choose the libtorrent version, get this warning : 

dpkg: warning: version 'repo' has bad syntax: version number does not start with digit 
Defaulting to libtorrent branch RC_1_2 for compatibility

## Reproduction steps
Run the Swizzin installation

## Installed applications through swizzin
nginx, rtorrent, autodl, panel, vsftpd, ffmpeg, quota

## Expected behavior
Be able to choose the libtorrent version

## Server Info
 - OS:Ubuntu Server 20.04.1
 - Image Source: Install from provider

## Is Swizzin up to date?
Fresh install today
HEAD is now at 65f8719 updated css aesthetics to address overlapping
Already up to date.

## Additional context
None

Thank you

**Comment by liaralabs** [comment]
Can you please provide further context?

What were you doing? Installing Deluge or qBittorrent? What selections did you make (versions, etc), etc.

It's possible this isn't fully an error, the message you received: `Defaulting to RC_1_2` indicates you have no other options to choose from for installing libtorrent.

**Comment by Nico83500** [comment]
I'm just trying to reinstall Swizzin to a new server but you're right, I also checked qBittorent without read it. The last time I installed Swizzin (august 2020) this software was not present and I checked all except Deluge. So I did the same thing, check all except Deluge.
I choosed rTorrent 0.9.8 and qBitorrent 4.1.7

**Comment by flying-sausages** [comment]
@liaralabs should we make a `while !choicescompatible; do choicemenu; done` type thing?

**Comment by liaralabs** [comment]
It looks like the issue is that "repo" versions aren't resolved while making the comparisons that the libtorrent whiptail is making.

I've added new "version" variables to the libtorrent checks, so this should be working now.

2f6a8d6cef2c549bc0fcd7ddfcf9907eaa9cb5ca

This logic is getting a little messy though and could probably be written in a cleaner way

**Comment by Nico83500** [comment]
Thank you, I'll try that ASAP. What is the "repo" version ? Is is better to use the repo version ? Thank you.

**Comment by liaralabs** [comment]
Repo is whatever is available via `apt`, anything else is compiled. The other versions are usually significantly more up-to-date, but take longer to install.
