### ISSUE TITLE
Bazarr installation pyenv: no such command `install'

### ISSUE THREAD

**Issue by Wyall** [liaralabs/swizzin#429]
## Bug description
During installation of bazarr a python environment is set up on Ubuntu 18.04, because Python 3.7 is needed and Ubuntu ships with 3.6. 
This is done in  swizzin/sources/functions/pyenv line 21.
line 26 is `/opt/pyenv/bin/pyenv install $version`
This results in ```pyenv: no such command `install' ```

Interestingly, Bazarr and Python 3.7 seem to be installed correctly.
```
sudo box install bazarr
Installing bazarr
Compiling Python 3.7.7. This may take some time ...
pyenv: no such command `install'
Cloning into '/opt/bazarr'
Checking python depends
Please ensure during bazarr wizard that baseurl is set to: /bazarr/
Created symlink /etc/systemd/system/multi-user.target.wants/bazarr.service → /etc/systemd/system/bazarr.service.
```

```
/opt/.venv/bazarr/bin/python --version
Python 3.7.7
```

## Reproduction steps
Install Bazarr, or
```
/opt/pyenv/bin/pyenv help install
pyenv: no such command `install'
```

## Installed applications through swizzin
(e.g. Nginx, ffmpeg, panel)

## Expected behavior
No error message

## Server Info
 - OS: Ubuntu 18.04
 - Image Source: Installscript from OneProvider, updated from 16.04 before installing Swizzin

## Is Swizzin up to date?

HEAD is now at dd93686

## Additional context
None

**Comment by flying-sausages** [comment]
1) please add logs and the info about your machine
2) bazarr is being installed through venv so you need to use the right binary

**Comment by liaralabs** [comment]
I can't reproduce this one

![installer](https://i.imgur.com/02uWkVb.png)

![status](https://i.imgur.com/QYLGgww.png)

**Comment by Wyall** [comment]
It got installed for me too, despite the error. Well it's weird, if it is not reproducible on a fresh system, then it doesn't really matter as far as I'm concerned. Should I close this then?

**Comment by liaralabs** [comment]
Yes. Feel free to re-open if something comes back or you can reproduce it.
