### ISSUE TITLE
New user sudo rules are not being set properly

### ISSUE THREAD

**Issue by nwcmn** [liaralabs/swizzin#43]
https://github.com/liaralabs/swizzin/blob/3823996715911cc64410a5d0dbe01a7f051d05a0/scripts/box#L278-L280

Looks like the wrong variable was used.

**Comment by liaralabs** [comment]
Not sure when this snuck in, pretty sure this was working properly at one point :smile: 

This should be fixed now. If you have users that were created with improper aliases, they should be fixed automatically by running `box update`. Take note that it will require two runs of `box update` to apply the changes made to the update script (one to pull the changes, and another to execute them -- first time only).
