### ISSUE TITLE
Jackett giving a 404 Error

### ISSUE THREAD

**Issue by bendobos** [liaralabs/swizzin#44]
The default config for Jackett seems to be broken in some way. Whenever I install it I get an `HTTP ERROR 404` when opening `https://MY.IP/jackett`. All other services are working fine.

From nginx `error.log`:
```
2017/11/30 18:19:28 [error] 2654#2654: *93 open() "/srv/jackett" failed (2: No such file or directory), client: XXX.XX.XXX.XXX, server: _, request: "GET /jackett HTTP/1.1", host: "62.210.141.162"
```

**Comment by liaralabs** [comment]
Jackett requires the trailing slash on the uri.

I might be able to clean this up with a redirect. Please try it and let me know if the trailing slash fixes your issue.

**Comment by bendobos** [comment]
My god. That fixes it! Having a note somewhere about that or not requiring a trailing `/` would be great, just to save people some time that might come after me.
