### ISSUE TITLE
Issue between ruTorrent and Remote Torrent Adder

### ISSUE THREAD

**Issue by Nico83500** [liaralabs/swizzin#441]
## Bug description
I have an issue between the Chrome/Edge extension Remote Torrent Adder and ruTorrent. The torrent is added to ruTorrent but I get an error notification.

## Reproduction steps
1. Install the Remote Torrent Adder extension and configure it
2. Add a torrent to ruTorrent

## Installed applications through swizzin
nginx, ffmpeg, panel, quota

## Expected behavior
Get a success notification

## Server Info
 - OS: Ubuntu Server 20.04.1 
 - Image Source: Install 18.04 from provider + upgrade to 20.04.1

## Is Swizzin up to date?
Yes, fresh install today

## Additional context
I already opened a ticket to Remote Torrent Adder and after analysis, the issue seems to come from ruTorrent implementation. You could find some informations here : https://github.com/bogenpirat/remote-torrent-adder/issues/295

Thank you !

**Comment by liaralabs** [comment]
Hi Nico,

I've just pushed a commit which fixes this issue for me locally. Can you please run `box update` and give it another shot?

**Comment by liaralabs** [comment]
I've just reverted -- there seems to be some oddities with argument strings as well which has thrown a wrench in my tests. I will need to do some further tests before pushing this one out.

**Comment by liaralabs** [comment]
Should be fixed now :+1:

**Comment by Nico83500** [comment]
Yes it works !! Thank you very much !
