### ISSUE TITLE
I'm not sure whether this is related to the script however my /torrents/rtorrent/has disappeared

### ISSUE THREAD

**Issue by tmm22** [liaralabs/swizzin#46]
I'm not sure whether this is related to the script however my /torrents/rtorrent/has disappeared and I  did not move it or delete it everything else seems to be accounted for however there is one weird folder inside /torrents it just has a date on it like I said not sure if it is related to the script but it didn't delete anything or moving anything
hopefully this can be resolved without needing to re-download everything
please note I use speech recognition software which is not always 100% accurate so I do apologise for anything that doesn't make sense or any spelling mistakes

**Comment by liaralabs** [comment]
This was handled privately and not really anything that should be affected by the swizzin core.

I'm really not sure what happened here; however here is a run down:

`ls -la ~/torrents` revealed that indeed the rtorrent folder was gone.

```
drwxr-xr-x 85 user user 16384 Dec  5 00:36  
drwxr-xr-x  4 user user  4096 Dec  5 00:39 .
drwxr-xr-x 10 user user  4096 Nov 30 20:37 ..
drwxr-xr-x  2 user user  4096 Nov 16 00:37 deluge
```

However, `df -h` revealed that there was not loads of free drive space. Curious. Perhaps the torrents are still there somewhere?

`du -h ~/torrents` revealed that torrents had been moved to a completely invisible directory: 

```
./ /
```

Strange! I was able to recover the invisible folder to its original name, rtorrent, with the command
```
mv "./ /" rtorrent
```

And poof! The files are back. Never seen anything like this before, but glad your files are safe.
