### ISSUE TITLE
Update install script for Ombi to v3

### ISSUE THREAD

**Issue by cyris69** [liaralabs/swizzin#48]
The v3 is now recommended but grabbed from here not git, https://ci.appveyor.com/project/tidusjar/requestplex/branch/DotNetCore/artifacts

**Comment by liaralabs** [comment]
Last time I checked, reverse proxy installs couldn't be automated and
required the user to define the url path manually from within the app after
install.

I am willing to update the install if you can confirm this is no longer the
case. I'm short on time to explore apps and their beta updates due to the
holidays and will be spending the next several days travelling.

**Comment by cyris69** [comment]
Sure, I can ask the dev today. Or, if you can tell me how to update url manually I'd do that as well. I was trying last night to figure it out.

**Comment by liaralabs** [comment]
This is the only info I see on writing reverse proxies -- it seems as if the rewrite is handled solely on nginx now, which could be good news.

https://github.com/tidusjar/Ombi/wiki/Nginx-Reverse-Proxy-examples-(Linux)

However, it will be some time until I have time to test.

**Comment by cyris69** [comment]
Also, the script inside QuickBox pulls v3 but I guess that doesn't matter as QB utilizes apache but I'm not a coder so not sure. I just want to make sure I'm understanded correctly, that I'm talking about when I type the install packagename command for ombi and its automated added to panel, rather than update an existing installation. Ombi requires a fresh install moving either directions so from v2 -> v3 or vice versa

https://github.com/QuickBox/QB/blob/master/packages/package/install/installpackage-ombi

**Comment by tidusjar** [comment]
Hey,

So I could make the base URL configurable via a startup argument if that would help you? Wouldn't be much work for me to do that.

**Comment by cyris69** [comment]
I guess I misspoke, @liaralabs I was merely speaking that your install script for Ombi pull the release via this link: https://ci.appveyor.com/api/buildjobs/34973ana21t6xyqm/artifacts/linux.tar.gz

Not how it's setup here:

`function _install() {
  cd /opt
  curl -sL https://git.io/vKEJz | grep release | grep zip | cut -d "\"" -f 2 | sed -e 's/\/tidusjar/https:\/\/github.com\/tidusjar/g' | xargs wget --quiet -O Ombi.zip >/dev/null 2>&1
  unzip Ombi.zip >/dev/null 2>&1
  mv Release ombi
  rm Ombi.zip
  chown -R ${user}: ombi
}`

**Comment by liaralabs** [comment]
@tidusjar a startup argument would be perfect! I can definitely work with that.

**Comment by cyris69** [comment]
@tidusjar did you ever get around to doing this?

**Comment by userdocs** [comment]
Resolved with this issue and commit but nit pushed to master.

https://github.com/tidusjar/Ombi/issues/2153

**Comment by liaralabs** [comment]
Finally, after a long wait, this has been pushed to the repo! Thanks for your patience :slightly_smiling_face: 

You can upgrade either by removing and reinstalling ombi or with the upgrade script. Note that v2 settings and DB are not compatible and will be deleted on upgrade.

**Comment by cyris69** [comment]
Glad to hear, I didn't get a notification about this and just happen to log into github. Since I have Ombi v3 installed already is there a way I can make the backend see it and add to the launch list on the web GUI? If I run the box install ombi will it just update any files that may be there from current install but then think it installed it just then?
