### ISSUE TITLE
SABNzbd redirects to localhost

### ISSUE THREAD

**Issue by d2dyno** [liaralabs/swizzin#5]
On fresh install, SAB redirects to `https://127.0.0.1:65080/sabnzbd/` when I click it from the apps menu on the left of the dashboard.

Edit: Also tried removing, reinstalling via `box install sabnzbd`. No errors, same issue.

**Comment by d2dyno** [comment]
This is because the dashboard is using https, but the port specified is the http port. We need to update this to use :65443.

**Comment by liaralabs** [comment]
No, I think it's actually the conf.d/proxy.conf file... It's the way it is because of sonarr, as it turns out Sonarr is the one that needs a special configuration and this config is the one that will break the other apps. I need to do a small refactoring of the proxy configs here.

**Comment by liaralabs** [comment]
This should be fixed with c5e8387a951a25984e23a75cff86adfcfa3a188e

Simple comment out the line: proxy_redirect  http://  \$scheme://;

In /etc/nginx/conf.d/proxy.conf to avoid a reinstall of nginx.
