### ISSUE TITLE
Nginx Theme not working

### ISSUE THREAD

**Issue by revunix** [liaralabs/swizzin#52]
Hello,

this nginx theme is not working.

Not found
``<link rel="stylesheet" href="/fancyindex-dark/styles.css">``
`` <script src="/Nginx-Fancyindex-Theme-dark/addNginxFancyIndexForm.js"></script>``

https://imgur.com/4D7xZ7s

**Comment by liaralabs** [comment]
It seems the author changed some stuff which broke my sed matching -- this has been fixed and you should be able to restore functionality by using `box update`
