### ISSUE TITLE
Quota

### ISSUE THREAD

**Issue by Kongledyret** [liaralabs/swizzin#53]
Hi, 
I've installed script with quotas. 
Quotas is successfully installed: 
Using root mount for quotas
Quotas have been installed. Use the command setdisk to set quotas per user.

But when using the mentioned command I get: 
Error: setdisk invalid command

Any idea?

**Comment by liaralabs** [comment]
Did you install quotas during your initial install?

If so, you'll need to `source /root/.profile` before the command `setdisk` becomes available (it's a custom script in the swizzin bins)

**Comment by Kongledyret** [comment]
Hi, 
I got the idea now. What I basicly did was to do box setdisk. I soon realized that the command setdisk was a simple command without the box in front. 

Thanks! Works now.
