### ISSUE TITLE
Add ability to see quotas in use

### ISSUE THREAD

**Issue by d2dyno** [liaralabs/swizzin#54]
Possibly similar to QB's 'showspace'. Unless this is already implemented and I missed it.

**Comment by liaralabs** [comment]
QB's `showspace` is superfluous. 3/4 of the code in that file could be accomplished by using the -h argument with du.

If you want to check quotas `repquota` is the command you need.

`repquota -avs` should display all quotas on your machine with verbose output and human readable values.
