### ISSUE TITLE
„box“ don't work any more

### ISSUE THREAD

**Issue by revunix** [liaralabs/swizzin#55]
Hello,

the „box“ command only works in the „root@box:/etc/swizzin/scripts“ folder, any idea?

**Comment by liaralabs** [comment]
Did you edit your .profile in /root?

This file is loaded each time you load a shell with that user and it should have the line 

`export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/bin/swizzin` (or something close)

If you altered your .profile or rewrote it, it's possible you removed the PATH variable which loads the swizzin scripts.

**Comment by revunix** [comment]
Works again, thanks.
i don't edited my .profile...

hmm
