### ISSUE TITLE
Error 502 on radarr, jackett & sonarr

### ISSUE THREAD

**Issue by bumjrah** [liaralabs/swizzin#57]
Funny enough plexpy works. 

I have tried removing mono & re-installing. Box remove & install again the above programs without any luck.

**Comment by liaralabs** [comment]
plexpy is not a mono app.

Have you tried running the command to start one of these apps directly from your user's shell?

`mono /opt/NzbDrone/NzbDrone.exe`

You might receive an error that will give a hint as to the issue preventing it from starting up.

**Comment by bumjrah** [comment]
~$ mono /opt/NzbDrone/NzbDrone.exe


Press enter to exit...



....

This is the response I get from running the command.

**Comment by liaralabs** [comment]
And the directory /opt/NzbDrone and all it's contents exist?

I may need to take a closer look to see what's going on. Any way you could get in touch in IRC or send me an email at liara [at] swizzin dot ltd?

**Comment by bumjrah** [comment]
Problem solved

**Comment by liaralabs** [comment]
To anyone curious: the issue was caused by changing the mono version to the alpha branch. Please note, only the software shipped inside swizzin is supported.
