### ISSUE TITLE
File Manager in ruTorrent

### ISSUE THREAD

**Issue by dwinnert** [liaralabs/swizzin#60]
Minor issue. I have the box uncheacked to show hidden files, yet hidden files still show. I know this is a minor issue and I have looked for solutions before posting here.

**Comment by liaralabs** [comment]
I cannot reproduce this issue locally.

Have you tried using another browser?

**Comment by dwinnert** [comment]
Yeah....it still does not stick. I'll post the issue on the authors Github page.

Thanks!
