### ISSUE TITLE
LXC Containers

### ISSUE THREAD

**Issue by RikT** [liaralabs/swizzin#62]
Just a question really will this run ok on an LXC container

**Comment by liaralabs** [comment]
There has been no testing for use with lxc

**Comment by RikT** [comment]
I am giving it a go now will report back if all goes well then

**Comment by RikT** [comment]
Just for the record it runs fine on LXC containers both ubuntu and debian

**Comment by liaralabs** [comment]
Thanks for giving it a test! Can you let me know which packages you tried, so I know which ones have been tested?

**Comment by strideynet** [comment]
I've got a fair bit of experience with LXC and there is no reason why this shouldn't run 100% okay within a container. The only module that should ever experience difficulties is stuff pertaining to VPNs which can take a bit of fiddling to get configured correctly.

**Comment by liaralabs** [comment]
Great! Then I will close this issue -- if bugs arise due to LXC containers in the future, please open a new issue in regards to the specific package.

Thanks!
