### ISSUE TITLE
Issue with btsync on clean install

### ISSUE THREAD

**Issue by tfp1** [liaralabs/swizzin#65]
```
Checking OS version and release ...
I have determined you are using Ubuntu 16.04.
Updating system and grabbing core dependencies.
Cloning swizzin repo to localhost
User directory already exists ...
Changing password to new password
Adding password for user [redacted]
Adding password for user [redacted]
Installing nginx
Installing rtorrent
Installing rTorrent Dependencies ...
Building xmlrpc-c from source ...
Building libtorrent from source ...
Building rtorrent from source ...
Making [redacted] directory structure ...
Setting permissions on [redacted] ...
setting up rtorrent.rc ...
Installing rutorrent
Installing panel
Installing ffmpeg
Installing btsync
cp: cannot stat '/var/run/resilio-sync/sync.pid': No such file or directory
```
Install then continued

**Comment by liaralabs** [comment]
I believe this error is running on a command that isn't actually doing anything important -- since this package was ported from QuickBox, I haven't done too much to the script itself. Did you test the application after install to see if it worked?

**Comment by jkristoph** [comment]
I have the same experience. In addition to this, installation creates a folder /home/rlsync with ownership and btsync cannot access user home folder where data is stored.

**Comment by tfp1** [comment]
@liaralabs yeah, btsync launches, but I get a database error whenever I try to add a folder. Tried to manage the permissions with chown and chmod, but that did not resolve the issue

**Comment by liaralabs** [comment]
This may have something to do with the recent home folder permission changes. Are you attempting to write into the user's data folder or just read?

Perhaps the solution here would be just to run the rlsync daemon as the master user.

**Comment by liaralabs** [comment]
Hey guys, so a `box update` should update your existing install to use your master user for the service.

You might need to rearrange some of your setups because the config dir has changed from /var/lib/resilio-sync to /home/user/.config/resilio-sync.

However, this should take care of the issues you've been seering.

Please let me know!

**Comment by tfp1** [comment]
Thanks for the fix!

In the interim I was able to get it working by [installing directly](https://help.resilio.com/hc/en-us/articles/206178924)

**Comment by jkristoph** [comment]
Great!

**Comment by liaralabs** [comment]
Closing due to no further input. Assuming no more issues -- please reopen if there are still permission issues
