### ISSUE TITLE
No command after reboot ?

### ISSUE THREAD

**Issue by mrlongshen** [liaralabs/swizzin#72]
I successful install swizz script at online dedicated server as root. After reboot, I try to run box list but not recognize. 

`root@localhost:~# box list
No command 'box' found, did you mean:
 Command 'gox' from package 'gox' (universe)
 Command 'wbox' from package 'wbox' (universe)
 Command 'tox' from package 'tox' (universe)
 Command 'rox' from package 'rox-filer' (universe)
 Command 'fox' from package 'objcryst-fox' (universe)
 Command 'eox' from package 'keyboards-rg' (universe)
 Command 'bob' from package 'python-sponge' (universe)
 Command 'rbox' from package 'qhull-bin' (universe)
 Command 'bbox' from package 'ps2eps' (main)
 Command 'vbox' from package 'isdnvboxclient' (universe)
 Command 'bos' from package 'openafs-client' (universe)
 Command 'sox' from package 'sox' (universe)
box: command not found
`

all swizzbox command missing. why ?

I have to run the script again to gain access all the command back. Is this a bugs ?

**Comment by liaralabs** [comment]
Do you have a file: `/root/.profile`?

Is the line: `export PATH=$PATH:/usr/local/bin/swizzin` at the bottom of it?

**Comment by mrlongshen** [comment]
I have this.

`
# ~/.profile: executed by Bourne-compatible login shells.

if [ "$BASH" ]; then
  if [ -f ~/.bashrc ]; then
    . ~/.bashrc
  fi
fi

mesg n || true
export PATH=$PATH:/usr/local/bin/swizzin
export PATH=$PATH:/usr/local/bin/swizzin
export PATH=$PATH:/usr/local/bin/swizzin
`

**Comment by liaralabs** [comment]
It should be loading the path when your login shell loads, if it's in .profile.

Have you changed your shell to something other than bash or made any other similar modifications?

**Comment by mrlongshen** [comment]
@liaralabs  nope. no changes anything. Just fresh install.

**Comment by aRnE-bd** [comment]
I also faced this problem. However the thing is the path is not loading. To fix it just manually run this command source /root/.profile  after that commands will work. this thing does not stick though. once you log out of ssh and log in again you need to re run this command

**Comment by liaralabs** [comment]
I cannot reproduce this guys, so I need a bit more info. .profile loads as it should for me on Debian 9 both through a direct connection to root and by executing sudo bash as a regular user. Box should also be found by using `sudo box` as the sudo paths are stored in sudoers.d.

Please let me know the following:

Distro of server:
SSH Client:
Does the file /root/.bash_profile exist?
Are you logging in directly to ssh as root? If no, does the behavior change if you do?

**Comment by aRnE-bd** [comment]
well debian 9 is good. This happens in ubuntu 16.04 SYS server.
