### ISSUE TITLE
Deluge-web broken on secondary users?

### ISSUE THREAD

**Issue by d2dyno** [liaralabs/swizzin#73]
I started investigating this issue when one of my users reported they got '500' errors when trying to load Deluge webui. It looks like the service is dying upon restart for some reason:

`systemctl status deluge-web@user2.service
● deluge-web@user2.service - Deluge Bittorrent Client Web Interface
   Loaded: loaded (/etc/systemd/system/deluge-web@.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2018-03-13 17:14:40 CET; 4min 51s ago
  Process: 38348 ExecStop=/usr/bin/killall -w -s 9 /usr/bin/deluge-web (code=exited, status=1/FAILURE)
 Main PID: 50742 (deluge-web)
   CGroup: /system.slice/system-deluge\x2dweb.slice/deluge-web@user2.service
           └─50742 /usr/bin/python /usr/bin/deluge-web`

The interesting thing is, the webui works on the primary/admin account.

**Comment by liaralabs** [comment]
Whoops! Guess I neglected to configure the nginx end for secondary users. You should be able to run a `box upgrade nginx` to fix your current install, but the recent commit will ensure newly created users will be able to access their installs.
