### ISSUE TITLE
Doesn't have a release file?

### ISSUE THREAD

**Issue by LaMpiR** [liaralabs/swizzin#76]
Hi,
I've run the update and one part was this:

>  34 files changed, 643 insertions(+), 134 deletions(-)
 create mode 100755 scripts/rtx
 create mode 100755 scripts/update/btsync.sh
 create mode 100755 scripts/update/lounge.sh
 create mode 100755 scripts/update/permissions.sh
 create mode 100755 scripts/update/rtorrent.sh
 create mode 100755 scripts/upgrade/autodl.sh
 create mode 100644 sources/network.port.patch
E: The repository 'http://ubuntu.mirrors.ovh.net/ubuntu zesty Release' does no longer have a Release file.
E: The repository 'http://ubuntu.mirrors.ovh.net/ubuntu zesty-updates Release' does no longer have a Release file.
E: The repository 'http://ubuntu.mirrors.ovh.net/ubuntu zesty-backports Release' does no longer have a Release file.
E: The repository 'http://security.ubuntu.com/ubuntu zesty-security Release' does no longer have a Release file.
grep: /etc/nginx/apps/dindex.conf: No such file or directory
Updating panel

> 

Afterwards, I've run it again, and everything was up-to-date. Is this normal?

**Comment by liaralabs** [comment]
The error you are seeing is on mirrors that I don't touch (I only add 3rd party repos, I do not modify official). It appears you are running a version of Ubuntu that has hit EOL, this is not a swizzin error. I recommend you dist-upgrade your OS to something that is still supported (i.e. 17.10 artful). There should be plenty of documentation on how to do this if you search around :smile:

**Comment by LaMpiR** [comment]
xx@xx:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty
xx@xx:~$

**Comment by liaralabs** [comment]
The errors above are directly from apt-get (just an apt-get update command being run from the script)

Since Zesty has reached end of life, you need to update to a version of Ubuntu which will still receive updates -- i.e. Ubuntu 17.10 or the upcoming 18.04 release (however, I have not yet tested swizzin with the new LTS release).

There is nothing I can do about decommissioned repositories for releases that have reached their end of life.

**Comment by LaMpiR** [comment]
Done. I am now on 17.10 and will wait for the 18.04 lts.

Would there be any chance of getting some help with this?

https://github.com/pannal/Sub-Zero.bundle/issues/505#issuecomment-384091903

I have no idea what to do to be honest.
