### ISSUE TITLE
Headphones does not start automatically

### ISSUE THREAD

**Issue by dangitDepa** [liaralabs/swizzin#77]
The headphones service does not automatically start after a reboot because of a missing folder in /var/run/headphones.
This folder is created on the installation but after a reboot, the folder is deleted because of the tmpfs filesystem of the /run and /var/run folders.
A simple fix would be creating a file in either
/etc/tmpfiles.d/, /run/tmpfiles.d/ or /usr/lib/tmpfiles.d/ with a configuration file like so:
[headphones.conf]
d /var/run/headphones 0755 [username] [group]
or creating the folder during boot in some other way, before starting headphones.

I don't know if the error was on my part, but i tried various installation and they all resulted in this problem.

**Comment by liaralabs** [comment]
Definitely not error on your part. I'm actually already creating a per-user folder with tmpfiles.d for the rtorrent sockets, so this will just be a quick modification of the systemd service to use the user folder rather than the headphones folder

**Comment by liaralabs** [comment]
Alright! This should be fixed as of 1d1288284d5c4d5bb44e3654c3c6bf3cced5f50d

`box update` should take care of your existing install, can you test and report?

**Comment by dangitDepa** [comment]
Seems to be working just fine.

**Comment by liaralabs** [comment]
Perfect! Closing this issue then :+1:
