### ISSUE TITLE
Install script hanging on "finalizing sendmail installation"

### ISSUE THREAD

**Issue by itsrajivshah** [liaralabs/swizzin#79]
I've noticed that when installing to a clean install of Ubuntu 16.04 on my dedicated server, that when you select CSF in the initial install of Swizzin, the installer hangs at "finalizing sendmail installation" until the SSH connection ends, though it appears that the script has continued running, as after a reboot the panel pops up and the program seems to behave normally.

**Comment by liaralabs** [comment]
Are the csf and lfd services running though? If the installer never finished, it's plausible the firewall rules never took hold (and you would never be the wiser)

`sudo systemctl status csf`
`sudo systemctl status lfd`

**Comment by itsrajivshah** [comment]
I just ran both commands and got `active (exited)` and `active (running)` respectively - so I guess it's working.

**Comment by austinthetaco** [comment]
@liaralabs i'm having this issue as well. it completely busted my install and i had to start over.

**Comment by liaralabs** [comment]
Issue directly with CSF which is now a deprecated package.
