### ISSUE TITLE
how can I move QB to this ?

### ISSUE THREAD

**Issue by RajPatel0929** [liaralabs/swizzin#8]
without remove all my torrents etc etc

**Comment by demonotaku** [comment]
Right now the Best approach would be to get a new box, install Swizzin, configure that box, LFTP tranfer data from one box to the other then copy your ,sessions file

**Comment by npab19** [comment]
I have a bash script that will copy all downloaded files and session files for you and put them in the correct location. Nothing fancy. I'll try and put it up later today.

**Comment by liaralabs** [comment]
Please guys, this is not a forum to start discussion threads - this is for reporting bugs to the project.

If you're interested in talking about the project, please join us in IRC or start a thread on reddit or something
