### ISSUE TITLE
Support for starting / stopping / restarting rtorrent

### ISSUE THREAD

**Issue by Placinta** [liaralabs/swizzin#83]
I looked through the source code a bit, and it doesn't seem that there are systemd services created for rtorrent / rutorrent.

Are there any plans to adding that? Currently I seem to have to rely on the restart feature in the panel.

**Comment by Placinta** [comment]
Nevermind, I was wrong. There is a service.

**Comment by liaralabs** [comment]
:wink: 

I'll likely be backporting the `box` service commands from swizzin.xl once I have a bit more time, but yes there are systemd services for everything :smile:
