### ISSUE TITLE
screen over tmux

### ISSUE THREAD

**Issue by Placinta** [liaralabs/swizzin#84]
Hi.

Just a personal preference I guess, but is there any reason why irssi and rtorrent are executed via screen and not tmux?

**Comment by liaralabs** [comment]
Personal preference. Plus, users of swizzin and QuickBox will already know how to attach and detach from screens -- it's been this way for years and I do not see a compelling reason to throw this out the window.

Is there a reason you prefer tmux over screen? I can't find any solid reasons that would give benefits and wouldn't result in me and every user needing to relearn how to do their existing workflows.

**Comment by Placinta** [comment]
I guess it's also personal preference. 

I use iterm2, and it has tmux integration, so that's convenient for tab / window management.
