### ISSUE TITLE
Request: Organizr Box Install

### ISSUE THREAD

**Issue by 2wenty2wo** [liaralabs/swizzin#85]
Hi,

What are the chances of adding a [Organizr](https://github.com/causefx/Organizr) installer script to box?

Kind Regards,
2wenty2wo

**Comment by liaralabs** [comment]
Feature requests now live on feathub (I've added it)

However, I'm not certain if I'll be adding a second panel like solution. It can be difficult on the back end to keep track of more than one solution that could live in your web root.
