### ISSUE TITLE
rTorrent not restarting

### ISSUE THREAD

**Issue by itskiru** [liaralabs/swizzin#86]
Hi,

I got a problem with rtorrents: the torrents didn't started.

So I decided to reboot the rTorrent service by the panel. But the light was always red. And when I go on ssh and try to see the service, I got that: ![status](https://a.lolisareinthe.club/bules.png)

And that, everytime I try to launch it. When I try to run the ExecStart command, nothing appear in `screen -ls`.

That's my journalctl result: ![journalctl](https://a.lolisareinthe.club/byusfy.png).

Thanks for the help !

**Comment by liaralabs** [comment]
The best way to troubleshoot rtorrent is to just run the command `rtorrent` as your user. If it fails to start, it'll issue an error with the exact problem
