### ISSUE TITLE
Quickstart as sudo problem ?

### ISSUE THREAD

**Issue by mrlongshen** [liaralabs/swizzin#88]
![2018-04-05 21_19_24-liaralabs_swizzin_ a simple modular seedbox solution](https://user-images.githubusercontent.com/5020778/38368162-280f25aa-3917-11e8-9b52-bb7d120bd96d.png)

I try to run as sudo and got this problem.
why ya ?

sudo -H bash <(wget -O- -q  https://raw.githubusercontent.com/liaralabs/swizzin/master/setup.sh)

and get this problem

`bash: /dev/fd/63: No such file or directory`

**Comment by liaralabs** [comment]
Does this work instead?

`sudo -H -c 'bash <(wget -O- -q https://raw.githubusercontent.com/liaralabs/swizzin/master/setup.sh)'`

**Comment by mrlongshen** [comment]
Hi @liaralabs , 
I have test it, and it working.
Here some proof.

`mrlongshen@testbox:~$ sudo -H su -c 'bash <(wget -O- -q https://raw.githubusercontent.com/liaralabs/swizzin/master/setup.sh)'
[sudo] password for mrlongshen:
Checking OS version and release ...
I have determined you are using Ubuntu 16.04.
Updating system and grabbing core dependencies.
Cloning swizzin repo to localhost
`

![2018-04-09 21_01_54-45 76 156 97 root](https://user-images.githubusercontent.com/5020778/38499155-459aed96-3c39-11e8-9246-dc62a649ab62.png)

**Comment by mrlongshen** [comment]
root@testbox:~# su - mrlongshen
mrlongshen@testbox:~$ sudo -H su -c 'bash <(wget -O- -q https://raw.githubusercontent.com/liaralabs/swizzin/master/setup.sh)'
[sudo] password for mrlongshen:
Checking OS version and release ...
I have determined you are using Ubuntu 16.04.
Updating system and grabbing core dependencies.
Cloning swizzin repo to localhost
Cracklib detected. Checking password strength.
OK.
Creating new user mrporno ...
Adding password for user mrporno
Adding password for user mrporno
Installing nginx
