### ISSUE TITLE
Add medusa support

### ISSUE THREAD

**Issue by smoresmores** [liaralabs/swizzin#9]
It would be awesome if you could add Medusa as an additional package option.
Medusa is same as SickRage but it gives you an option to select the torrent your want to download manually. It's great imo and would love to see it integrated here.
https://github.com/pymedusa/Medusa

**Comment by liaralabs** [comment]
I personally prefer Medusa over sickrage, but haven't gotten around to implementing it yet. It's definitely on my to-do list :)

**Comment by liaralabs** [comment]
Added with commit f073520b1e3e7df7da3658961738027f11d35288
