### ISSUE TITLE
SCGI port missing on dashboard

### ISSUE THREAD

**Issue by Hottwire** [liaralabs/swizzin#95]
On the dashboard you can hover for the scgi port for rtorrent. However it simply displays a scgi port : HERE--

Is there any way to fix this if the port is enabled. 
I need this to enable couchpotato to use rtorrent as a download client.

Alternatively just knowing how to point to rtorrent from couchpotato/sonarr/radarr etc would work.

**Comment by liaralabs** [comment]
I can't really recommend it -- next time you run box update, it'll switch you back to the unix socket.

Have you tried [this wiki](https://github.com/liaralabs/swizzin/wiki/How-to-connect-rTorrent-&-Deluge-with-Sonarr-&-Radarr)?

**Comment by Hottwire** [comment]
Well if its not recommended then no issues. 

I managed to get both couchpotato and radarr working using that wiki
