### ISSUE TITLE
Ubuntu 18.04

### ISSUE THREAD

**Issue by RikT** [liaralabs/swizzin#96]
Tried to do an install but says unsupported as this is the new LTS is this going to be supported and if so roughly how long?

**Comment by liaralabs** [comment]
I will be supporting the lts release once it is released. As it stands, 18.04 is still considered beta until tomorrow. Then, I will begin testing once one of my testbeds offers an image.

I'm not going out of my way to setup a custom test environment for a beta os/providers who don't yet offer support for the release.
